// https://syzkaller.appspot.com/bug?id=badad2dede6b94b2b829498e485cd76573e37d4f
// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <dirent.h>
#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <setjmp.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <sys/mount.h>
#include <sys/prctl.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

#include <linux/loop.h>

#ifndef __NR_memfd_create
#define __NR_memfd_create 319
#endif
#ifndef __NR_renameat2
#define __NR_renameat2 316
#endif

static unsigned long long procid;

static void sleep_ms(uint64_t ms)
{
  usleep(ms * 1000);
}

static uint64_t current_time_ms(void)
{
  struct timespec ts;
  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    exit(1);
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

static bool write_file(const char* file, const char* what, ...)
{
  char buf[1024];
  va_list args;
  va_start(args, what);
  vsnprintf(buf, sizeof(buf), what, args);
  va_end(args);
  buf[sizeof(buf) - 1] = 0;
  int len = strlen(buf);
  int fd = open(file, O_WRONLY | O_CLOEXEC);
  if (fd == -1)
    return false;
  if (write(fd, buf, len) != len) {
    int err = errno;
    close(fd);
    errno = err;
    return false;
  }
  close(fd);
  return true;
}

//% This code is derived from puff.{c,h}, found in the zlib development. The
//% original files come with the following copyright notice:

//% Copyright (C) 2002-2013 Mark Adler, all rights reserved
//% version 2.3, 21 Jan 2013
//% This software is provided 'as-is', without any express or implied
//% warranty.  In no event will the author be held liable for any damages
//% arising from the use of this software.
//% Permission is granted to anyone to use this software for any purpose,
//% including commercial applications, and to alter it and redistribute it
//% freely, subject to the following restrictions:
//% 1. The origin of this software must not be misrepresented; you must not
//%    claim that you wrote the original software. If you use this software
//%    in a product, an acknowledgment in the product documentation would be
//%    appreciated but is not required.
//% 2. Altered source versions must be plainly marked as such, and must not be
//%    misrepresented as being the original software.
//% 3. This notice may not be removed or altered from any source distribution.
//% Mark Adler    madler@alumni.caltech.edu

//% BEGIN CODE DERIVED FROM puff.{c,h}

#define MAXBITS 15
#define MAXLCODES 286
#define MAXDCODES 30
#define MAXCODES (MAXLCODES + MAXDCODES)
#define FIXLCODES 288

struct puff_state {
  unsigned char* out;
  unsigned long outlen;
  unsigned long outcnt;
  const unsigned char* in;
  unsigned long inlen;
  unsigned long incnt;
  int bitbuf;
  int bitcnt;
  jmp_buf env;
};
static int puff_bits(struct puff_state* s, int need)
{
  long val = s->bitbuf;
  while (s->bitcnt < need) {
    if (s->incnt == s->inlen)
      longjmp(s->env, 1);
    val |= (long)(s->in[s->incnt++]) << s->bitcnt;
    s->bitcnt += 8;
  }
  s->bitbuf = (int)(val >> need);
  s->bitcnt -= need;
  return (int)(val & ((1L << need) - 1));
}
static int puff_stored(struct puff_state* s)
{
  s->bitbuf = 0;
  s->bitcnt = 0;
  if (s->incnt + 4 > s->inlen)
    return 2;
  unsigned len = s->in[s->incnt++];
  len |= s->in[s->incnt++] << 8;
  if (s->in[s->incnt++] != (~len & 0xff) ||
      s->in[s->incnt++] != ((~len >> 8) & 0xff))
    return -2;
  if (s->incnt + len > s->inlen)
    return 2;
  if (s->outcnt + len > s->outlen)
    return 1;
  for (; len--; s->outcnt++, s->incnt++) {
    if (s->in[s->incnt])
      s->out[s->outcnt] = s->in[s->incnt];
  }
  return 0;
}
struct puff_huffman {
  short* count;
  short* symbol;
};
static int puff_decode(struct puff_state* s, const struct puff_huffman* h)
{
  int first = 0;
  int index = 0;
  int bitbuf = s->bitbuf;
  int left = s->bitcnt;
  int code = first = index = 0;
  int len = 1;
  short* next = h->count + 1;
  while (1) {
    while (left--) {
      code |= bitbuf & 1;
      bitbuf >>= 1;
      int count = *next++;
      if (code - count < first) {
        s->bitbuf = bitbuf;
        s->bitcnt = (s->bitcnt - len) & 7;
        return h->symbol[index + (code - first)];
      }
      index += count;
      first += count;
      first <<= 1;
      code <<= 1;
      len++;
    }
    left = (MAXBITS + 1) - len;
    if (left == 0)
      break;
    if (s->incnt == s->inlen)
      longjmp(s->env, 1);
    bitbuf = s->in[s->incnt++];
    if (left > 8)
      left = 8;
  }
  return -10;
}
static int puff_construct(struct puff_huffman* h, const short* length, int n)
{
  int len;
  for (len = 0; len <= MAXBITS; len++)
    h->count[len] = 0;
  int symbol;
  for (symbol = 0; symbol < n; symbol++)
    (h->count[length[symbol]])++;
  if (h->count[0] == n)
    return 0;
  int left = 1;
  for (len = 1; len <= MAXBITS; len++) {
    left <<= 1;
    left -= h->count[len];
    if (left < 0)
      return left;
  }
  short offs[MAXBITS + 1];
  offs[1] = 0;
  for (len = 1; len < MAXBITS; len++)
    offs[len + 1] = offs[len] + h->count[len];
  for (symbol = 0; symbol < n; symbol++)
    if (length[symbol] != 0)
      h->symbol[offs[length[symbol]]++] = symbol;
  return left;
}
static int puff_codes(struct puff_state* s, const struct puff_huffman* lencode,
                      const struct puff_huffman* distcode)
{
  static const short lens[29] = {3,  4,  5,  6,   7,   8,   9,   10,  11, 13,
                                 15, 17, 19, 23,  27,  31,  35,  43,  51, 59,
                                 67, 83, 99, 115, 131, 163, 195, 227, 258};
  static const short lext[29] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2,
                                 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 0};
  static const short dists[30] = {
      1,    2,    3,    4,    5,    7,    9,    13,    17,    25,
      33,   49,   65,   97,   129,  193,  257,  385,   513,   769,
      1025, 1537, 2049, 3073, 4097, 6145, 8193, 12289, 16385, 24577};
  static const short dext[30] = {0, 0, 0,  0,  1,  1,  2,  2,  3,  3,
                                 4, 4, 5,  5,  6,  6,  7,  7,  8,  8,
                                 9, 9, 10, 10, 11, 11, 12, 12, 13, 13};
  int symbol;
  do {
    symbol = puff_decode(s, lencode);
    if (symbol < 0)
      return symbol;
    if (symbol < 256) {
      if (s->outcnt == s->outlen)
        return 1;
      if (symbol)
        s->out[s->outcnt] = symbol;
      s->outcnt++;
    } else if (symbol > 256) {
      symbol -= 257;
      if (symbol >= 29)
        return -10;
      int len = lens[symbol] + puff_bits(s, lext[symbol]);
      symbol = puff_decode(s, distcode);
      if (symbol < 0)
        return symbol;
      unsigned dist = dists[symbol] + puff_bits(s, dext[symbol]);
      if (dist > s->outcnt)
        return -11;
      if (s->outcnt + len > s->outlen)
        return 1;
      while (len--) {
        if (dist <= s->outcnt && s->out[s->outcnt - dist])
          s->out[s->outcnt] = s->out[s->outcnt - dist];
        s->outcnt++;
      }
    }
  } while (symbol != 256);
  return 0;
}
static int puff_fixed(struct puff_state* s)
{
  static int virgin = 1;
  static short lencnt[MAXBITS + 1], lensym[FIXLCODES];
  static short distcnt[MAXBITS + 1], distsym[MAXDCODES];
  static struct puff_huffman lencode, distcode;
  if (virgin) {
    lencode.count = lencnt;
    lencode.symbol = lensym;
    distcode.count = distcnt;
    distcode.symbol = distsym;
    short lengths[FIXLCODES];
    int symbol;
    for (symbol = 0; symbol < 144; symbol++)
      lengths[symbol] = 8;
    for (; symbol < 256; symbol++)
      lengths[symbol] = 9;
    for (; symbol < 280; symbol++)
      lengths[symbol] = 7;
    for (; symbol < FIXLCODES; symbol++)
      lengths[symbol] = 8;
    puff_construct(&lencode, lengths, FIXLCODES);
    for (symbol = 0; symbol < MAXDCODES; symbol++)
      lengths[symbol] = 5;
    puff_construct(&distcode, lengths, MAXDCODES);
    virgin = 0;
  }
  return puff_codes(s, &lencode, &distcode);
}
static int puff_dynamic(struct puff_state* s)
{
  static const short order[19] = {16, 17, 18, 0, 8,  7, 9,  6, 10, 5,
                                  11, 4,  12, 3, 13, 2, 14, 1, 15};
  int nlen = puff_bits(s, 5) + 257;
  int ndist = puff_bits(s, 5) + 1;
  int ncode = puff_bits(s, 4) + 4;
  if (nlen > MAXLCODES || ndist > MAXDCODES)
    return -3;
  short lengths[MAXCODES];
  int index;
  for (index = 0; index < ncode; index++)
    lengths[order[index]] = puff_bits(s, 3);
  for (; index < 19; index++)
    lengths[order[index]] = 0;
  short lencnt[MAXBITS + 1], lensym[MAXLCODES];
  struct puff_huffman lencode = {lencnt, lensym};
  int err = puff_construct(&lencode, lengths, 19);
  if (err != 0)
    return -4;
  index = 0;
  while (index < nlen + ndist) {
    int symbol;
    int len;
    symbol = puff_decode(s, &lencode);
    if (symbol < 0)
      return symbol;
    if (symbol < 16)
      lengths[index++] = symbol;
    else {
      len = 0;
      if (symbol == 16) {
        if (index == 0)
          return -5;
        len = lengths[index - 1];
        symbol = 3 + puff_bits(s, 2);
      } else if (symbol == 17)
        symbol = 3 + puff_bits(s, 3);
      else
        symbol = 11 + puff_bits(s, 7);
      if (index + symbol > nlen + ndist)
        return -6;
      while (symbol--)
        lengths[index++] = len;
    }
  }
  if (lengths[256] == 0)
    return -9;
  err = puff_construct(&lencode, lengths, nlen);
  if (err && (err < 0 || nlen != lencode.count[0] + lencode.count[1]))
    return -7;
  short distcnt[MAXBITS + 1], distsym[MAXDCODES];
  struct puff_huffman distcode = {distcnt, distsym};
  err = puff_construct(&distcode, lengths + nlen, ndist);
  if (err && (err < 0 || ndist != distcode.count[0] + distcode.count[1]))
    return -8;
  return puff_codes(s, &lencode, &distcode);
}
static int puff(unsigned char* dest, unsigned long* destlen,
                const unsigned char* source, unsigned long sourcelen)
{
  struct puff_state s = {
      .out = dest,
      .outlen = *destlen,
      .outcnt = 0,
      .in = source,
      .inlen = sourcelen,
      .incnt = 0,
      .bitbuf = 0,
      .bitcnt = 0,
  };
  int err;
  if (setjmp(s.env) != 0)
    err = 2;
  else {
    int last;
    do {
      last = puff_bits(&s, 1);
      int type = puff_bits(&s, 2);
      err = type == 0 ? puff_stored(&s)
                      : (type == 1 ? puff_fixed(&s)
                                   : (type == 2 ? puff_dynamic(&s) : -1));
      if (err != 0)
        break;
    } while (!last);
  }
  *destlen = s.outcnt;
  return err;
}

//% END CODE DERIVED FROM puff.{c,h}

#define ZLIB_HEADER_WIDTH 2

static int puff_zlib_to_file(const unsigned char* source,
                             unsigned long sourcelen, int dest_fd)
{
  if (sourcelen < ZLIB_HEADER_WIDTH)
    return 0;
  source += ZLIB_HEADER_WIDTH;
  sourcelen -= ZLIB_HEADER_WIDTH;
  const unsigned long max_destlen = 132 << 20;
  void* ret = mmap(0, max_destlen, PROT_WRITE | PROT_READ,
                   MAP_PRIVATE | MAP_ANON, -1, 0);
  if (ret == MAP_FAILED)
    return -1;
  unsigned char* dest = (unsigned char*)ret;
  unsigned long destlen = max_destlen;
  int err = puff(dest, &destlen, source, sourcelen);
  if (err) {
    munmap(dest, max_destlen);
    errno = -err;
    return -1;
  }
  if (write(dest_fd, dest, destlen) != (ssize_t)destlen) {
    munmap(dest, max_destlen);
    return -1;
  }
  return munmap(dest, max_destlen);
}

static int setup_loop_device(unsigned char* data, unsigned long size,
                             const char* loopname, int* loopfd_p)
{
  int err = 0, loopfd = -1;
  int memfd = syscall(__NR_memfd_create, "syzkaller", 0);
  if (memfd == -1) {
    err = errno;
    goto error;
  }
  if (puff_zlib_to_file(data, size, memfd)) {
    err = errno;
    goto error_close_memfd;
  }
  loopfd = open(loopname, O_RDWR);
  if (loopfd == -1) {
    err = errno;
    goto error_close_memfd;
  }
  if (ioctl(loopfd, LOOP_SET_FD, memfd)) {
    if (errno != EBUSY) {
      err = errno;
      goto error_close_loop;
    }
    ioctl(loopfd, LOOP_CLR_FD, 0);
    usleep(1000);
    if (ioctl(loopfd, LOOP_SET_FD, memfd)) {
      err = errno;
      goto error_close_loop;
    }
  }
  close(memfd);
  *loopfd_p = loopfd;
  return 0;

error_close_loop:
  close(loopfd);
error_close_memfd:
  close(memfd);
error:
  errno = err;
  return -1;
}

static void reset_loop_device(const char* loopname)
{
  int loopfd = open(loopname, O_RDWR);
  if (loopfd == -1) {
    return;
  }
  if (ioctl(loopfd, LOOP_CLR_FD, 0)) {
  }
  close(loopfd);
}

static long syz_mount_image(volatile long fsarg, volatile long dir,
                            volatile long flags, volatile long optsarg,
                            volatile long change_dir,
                            volatile unsigned long size, volatile long image)
{
  unsigned char* data = (unsigned char*)image;
  int res = -1, err = 0, need_loop_device = !!size;
  char* mount_opts = (char*)optsarg;
  char* target = (char*)dir;
  char* fs = (char*)fsarg;
  char* source = NULL;
  char loopname[64];
  if (need_loop_device) {
    int loopfd;
    memset(loopname, 0, sizeof(loopname));
    snprintf(loopname, sizeof(loopname), "/dev/loop%llu", procid);
    if (setup_loop_device(data, size, loopname, &loopfd) == -1)
      return -1;
    close(loopfd);
    source = loopname;
  }
  mkdir(target, 0777);
  char opts[256];
  memset(opts, 0, sizeof(opts));
  if (strlen(mount_opts) > (sizeof(opts) - 32)) {
  }
  strncpy(opts, mount_opts, sizeof(opts) - 32);
  if (strcmp(fs, "iso9660") == 0) {
    flags |= MS_RDONLY;
  } else if (strncmp(fs, "ext", 3) == 0) {
    bool has_remount_ro = false;
    char* remount_ro_start = strstr(opts, "errors=remount-ro");
    if (remount_ro_start != NULL) {
      char after = *(remount_ro_start + strlen("errors=remount-ro"));
      char before = remount_ro_start == opts ? '\0' : *(remount_ro_start - 1);
      has_remount_ro = ((before == '\0' || before == ',') &&
                        (after == '\0' || after == ','));
    }
    if (strstr(opts, "errors=panic") || !has_remount_ro)
      strcat(opts, ",errors=continue");
  } else if (strcmp(fs, "xfs") == 0) {
    strcat(opts, ",nouuid");
  }
  res = mount(source, target, fs, flags, opts);
  if (res == -1) {
    err = errno;
    goto error_clear_loop;
  }
  res = open(target, O_RDONLY | O_DIRECTORY);
  if (res == -1) {
    err = errno;
    goto error_clear_loop;
  }
  if (change_dir) {
    res = chdir(target);
    if (res == -1) {
      err = errno;
    }
  }

error_clear_loop:
  if (need_loop_device)
    reset_loop_device(loopname);
  errno = err;
  return res;
}

static void kill_and_wait(int pid, int* status)
{
  kill(-pid, SIGKILL);
  kill(pid, SIGKILL);
  for (int i = 0; i < 100; i++) {
    if (waitpid(-1, status, WNOHANG | __WALL) == pid)
      return;
    usleep(1000);
  }
  DIR* dir = opendir("/sys/fs/fuse/connections");
  if (dir) {
    for (;;) {
      struct dirent* ent = readdir(dir);
      if (!ent)
        break;
      if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0)
        continue;
      char abort[300];
      snprintf(abort, sizeof(abort), "/sys/fs/fuse/connections/%s/abort",
               ent->d_name);
      int fd = open(abort, O_WRONLY);
      if (fd == -1) {
        continue;
      }
      if (write(fd, abort, 1) < 0) {
      }
      close(fd);
    }
    closedir(dir);
  } else {
  }
  while (waitpid(-1, status, __WALL) != pid) {
  }
}

static void reset_loop()
{
  char buf[64];
  snprintf(buf, sizeof(buf), "/dev/loop%llu", procid);
  int loopfd = open(buf, O_RDWR);
  if (loopfd != -1) {
    ioctl(loopfd, LOOP_CLR_FD, 0);
    close(loopfd);
  }
}

static void setup_test()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  setpgrp();
  write_file("/proc/self/oom_score_adj", "1000");
}

static void execute_one(void);

#define WAIT_FLAGS __WALL

static void loop(void)
{
  int iter = 0;
  for (;; iter++) {
    reset_loop();
    int pid = fork();
    if (pid < 0)
      exit(1);
    if (pid == 0) {
      setup_test();
      execute_one();
      exit(0);
    }
    int status = 0;
    uint64_t start = current_time_ms();
    for (;;) {
      sleep_ms(10);
      if (waitpid(-1, &status, WNOHANG | WAIT_FLAGS) == pid)
        break;
      if (current_time_ms() - start < 5000)
        continue;
      kill_and_wait(pid, &status);
      break;
    }
  }
}

uint64_t r[1] = {0xffffffffffffffff};

void execute_one(void)
{
  intptr_t res = 0;
  if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {
  }
  memcpy((void*)0x200000000140, "hfsplus\000", 8);
  memcpy((void*)0x200000000980,
         "\023\023w\305\3745\324\024T\325\324\035)\255\032`)"
         "Y\201F\346\276\026nA\255\r\275@T\003<\2373\273\332\202$"
         "\242\363\327r\347cnH\263<\277p\203r\350\361\271\223>"
         "\305\022wC\276\"\006 \236\360-\371\313\362\366\350\200\3238/\000",
         78);
  memcpy((void*)0x2000000001c0, "nobarrier", 9);
  *(uint8_t*)0x2000000001c9 = 0x2c;
  memcpy((void*)0x2000000001ca, "part", 4);
  *(uint8_t*)0x2000000001ce = 0x3d;
  sprintf((char*)0x2000000001cf, "0x%016llx", (long long)9);
  *(uint8_t*)0x2000000001e1 = 0x2c;
  memcpy((void*)0x2000000001e2, "umask", 5);
  *(uint8_t*)0x2000000001e7 = 0x3d;
  sprintf((char*)0x2000000001e8, "%023llo", (long long)0x800);
  *(uint8_t*)0x2000000001ff = 0x2c;
  memcpy((void*)0x200000000200, "nls", 3);
  *(uint8_t*)0x200000000203 = 0x3d;
  memcpy((void*)0x200000000204, "default", 7);
  *(uint8_t*)0x20000000020b = 0x2c;
  memcpy((void*)0x20000000020c, "type", 4);
  *(uint8_t*)0x200000000210 = 0x3d;
  memcpy((void*)0x200000000211, "\xf2\x68\xd6\x51", 4);
  *(uint8_t*)0x200000000215 = 0x2c;
  memcpy((void*)0x200000000216, "nodecompose", 11);
  *(uint8_t*)0x200000000221 = 0x2c;
  *(uint8_t*)0x200000000222 = 0;
  memcpy(
      (void*)0x200000000280,
      "\x78\x9c\xec\xdd\x4f\x88\x1c\x59\x1d\x07\xf0\x6f\x75\x26\x3d\xe9\x08\xd9"
      "\xd9\x7f\xd9\x28\x42\x86\x0d\x2c\xba\xc1\x64\x26\xcd\x9a\x08\xc2\x46\x11"
      "\xc9\x21\x48\xd0\xcb\x5e\x87\x64\xb2\x19\x32\xc9\x2e\x93\x59\xc9\x2e\x62"
      "\x3a\xea\x2a\x78\xf2\x24\x7b\xf0\xb0\x22\xf1\xb0\x22\x88\x88\xb0\x9e\x16"
      "\xd7\xb3\x20\x78\xf1\x94\x7b\xc0\x9b\x87\x1c\xd4\x91\xfa\xd3\x33\x3d\x33"
      "\x9d\x49\x4f\x92\x99\x1e\x77\x3f\x1f\xa8\xae\xf7\xfa\xbd\x7a\xef\x57\xbf"
      "\x54\x55\x77\x57\x67\xe8\x00\x9f\x5a\xe7\x5e\xcb\xfe\x5e\x8a\x9c\x3b\x7e"
      "\xfe\x66\x59\xbf\x7b\xa7\xbb\x78\xf7\x4e\xf7\x5a\xbf\x9c\x64\x32\x49\x2b"
      "\x99\xa8\x57\x29\x3a\x49\xf1\x71\x72\x36\xf5\x92\xcf\x96\x4f\x36\xc3\x15"
      "\x0f\x9a\xe7\x95\x7b\x1f\x16\x13\xef\x7d\xd0\xad\x6b\x13\xcd\x52\xf5\x6f"
      "\x6d\xb5\xdd\x26\x43\x7b\xf6\x92\x03\xab\x95\x7d\x49\xa6\xeb\xe2\xbf\x47"
      "\x1e\x76\xd3\x78\xd5\x52\x8d\x73\x71\x6d\xbc\x47\x54\xac\xc6\x5d\x26\xec"
      "\x58\x3f\x71\x30\x6e\x2b\x9b\xf4\xd6\x1a\x5b\x0f\xdd\x7c\xf4\xf3\x16\xd8"
      "\xb3\x6e\xd5\xaf\x9b\x9b\x4c\x25\x07\x53\xbf\xba\x96\xef\x03\xd2\x5c\x1d"
      "\x1e\x7e\x65\x18\x87\xce\xba\xda\x96\xd7\xa6\xde\x4e\xc7\x02\x00\x00\x00"
      "\x3b\x6f\xe8\x67\xf9\x41\x4f\xdd\xcf\xfd\xdc\xcc\xa1\xdd\x09\x07\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x3e\x19\x8a\xfa\x37\x03\x8b\x66\x69\xf5\xcb"
      "\xd3\x29\xfa\xbf\xff\xdf\x1e\xf8\x4d\xfd\xf6\x98\xc3\x7d\x4c\xef\x5e\xae"
      "\x56\xdf\x7e\x6a\xdc\x81\x00\x00\x00\x00\x00\x00\x00\xc0\x63\x39\x7a\x3f"
      "\xf7\x73\x33\x87\xfa\xf5\x95\xa2\xfa\xce\xff\xc5\xaa\xf2\x5c\xf5\xf8\x99"
      "\xbc\x95\x1b\x99\xcf\x52\x4e\xe4\x66\xe6\xb2\x9c\xe5\x2c\x65\x36\xc9\xd4"
      "\xc0\x40\xed\x9b\x73\xcb\xcb\x4b\xb3\x9b\xb7\xfc\x79\xca\x2d\x57\x56\x56"
      "\x6e\x35\x5b\x9e\x1a\xba\xe5\xa9\xf5\x71\xf5\x36\x06\x3a\xec\x7f\x1a\x6c"
      "\xea\x04\x00\x00\x00\x00\x00\x00\x00\x9f\x5a\x3f\xc8\xb9\xb5\xef\xff\x01"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x60\x2f\x28\x92\x7d\xf5\xaa\x5a"
      "\x9e\xeb\x97\xa7\xd2\x9a\x48\x72\x20\x49\xbb\x98\x5e\xed\xde\x1e\x6b\xb0"
      "\x8f\xa5\x0e\xfd\xa3\x71\x87\x01\x00\x00\x00\xbb\xe7\x50\xf1\xdf\xba\xb0"
      "\x52\x54\x9f\xf9\x0f\x57\x9f\xfb\x0f\xe4\xad\x5c\xcf\x72\x16\xb2\x9c\xc5"
      "\xcc\xe7\x52\x75\x2f\xa0\xfe\xe8\xdc\xfa\x5b\xaf\xbb\x78\xf7\x4e\xf7\x5a"
      "\xb9\x6c\x1e\xf0\x6b\xff\xdc\xd6\xfc\xd5\x88\xa9\xef\x3d\x0c\x9f\x79\xa6"
      "\xea\xf1\xfc\xea\x16\xe7\xf2\xcd\x7c\x27\xc7\x33\x9d\x0b\x59\xca\x42\xbe"
      "\x9b\xb9\x2c\x67\x3e\xd3\xf9\x46\x55\x9a\x4b\x91\xa9\xe6\xee\xc5\xd4\xdd"
      "\x3b\x9d\xf4\x63\xdd\x1c\xef\xd9\x75\xb5\x0b\x1b\x63\x3b\x3a\x50\x2e\xe3"
      "\x3b\x52\x45\xd2\xc9\xe5\x2c\x54\xb1\x9d\xc8\xc5\x76\x3f\xf4\x56\xd3\xef"
      "\xc8\xc0\x6c\x7f\x6c\x27\x1b\x66\xbc\x5d\x66\xa7\x78\xb5\x31\x62\x8e\x2e"
      "\x35\xeb\x72\x8f\x7e\xd6\xac\xf7\x86\xa9\x6a\xcf\xf7\xaf\x66\x64\xa6\xc9"
      "\x7d\x99\x8d\xa7\x07\xf3\xbe\x39\xf7\xdb\x3c\x4e\x36\xce\x34\x9b\xd6\xea"
      "\x3d\xa8\xe7\xd6\x66\x29\xab\x1b\x67\x7a\xa4\x9c\x1f\x6c\xd6\xbb\x90\xeb"
      "\x6d\xde\x4a\x5b\x9f\x89\xde\x4f\xcb\x5a\xff\xe8\x3b\xbc\x75\xce\x93\x2f"
      "\xfe\xfd\xcf\x17\xae\xb4\xae\x5f\xbd\x72\xf9\xc6\xf1\xbd\x73\x18\x3d\xa2"
      "\x8d\xc7\x44\x77\x20\x13\x2f\x8c\x94\x89\xc5\x32\x13\xbd\xc7\xc8\xc4\x81"
      "\xc7\x89\xff\xc9\x69\x37\xd9\xa8\xaf\xa2\xdb\xbb\x5a\xbe\x58\x6d\x7b\x28"
      "\x0b\xf9\x56\xde\xc8\xa5\xcc\xe7\x74\x66\x32\x9b\x33\x99\xc9\x57\x72\x2a"
      "\xdd\x9c\x1a\xc8\xeb\xf3\x5b\xe7\xb5\x3a\xd7\x5a\xdb\x3b\xd7\x8e\x7d\xa1"
      "\x29\x74\x92\xfc\xa4\x59\xef\xaa\xc9\x07\x35\x94\x79\x7d\x7a\x20\xaf\x83"
      "\x57\xba\xa9\xaa\x6d\xf0\x99\xb5\x2c\x3d\x33\x42\x96\x8a\x76\x86\x67\xe9"
      "\x1f\x43\x43\x99\xf8\x5c\x53\x28\xe7\xf8\xe1\xc0\x2b\xce\xf8\x6d\xcc\xc4"
      "\xec\x40\x26\x9e\xdd\x3a\x13\xbf\xfc\xcf\x4a\x92\x1b\x8b\xd7\xaf\x2e\x5d"
      "\x99\x7b\x73\xc4\xf9\x5e\x6a\xd6\xe5\x69\xfb\xee\xfa\x6b\xf4\xaf\x9e\xc8"
      "\x0e\x6d\x5f\xb3\xbb\xe5\xf1\xf2\x4c\xf9\x8f\x55\x56\x7e\x9c\x75\x47\x47"
      "\xd9\xf6\x6c\xbf\x6d\x43\xbe\xda\xcd\x37\x2e\x13\xcd\x60\xeb\xda\xda\xa9"
      "\xce\xe7\xba\xed\x61\x67\x6a\x39\xd2\xe1\xdb\xc3\x46\xaa\xdb\x5e\x18\x3a"
      "\x4b\xb7\x6a\x3b\x32\xd0\xb6\xee\x5d\x4e\xde\xc8\xe2\xea\xbb\x10\x00\xf6"
      "\xac\x56\x0e\xbe\x7c\xb0\xdd\xb9\xd7\xf9\x6b\xe7\xfd\xce\x8f\x3a\x57\x3a"
      "\xe7\x0f\x7c\x7d\xf2\xcc\xe4\xe7\xdb\xd9\xff\x97\x89\x3f\xed\xfb\x5d\xeb"
      "\xd7\xad\xaf\x16\x2f\xe7\xfd\x7c\x3f\x87\xc6\x1d\x2b\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x7c\x12\xdc\x78\xfb\x9d\xab\x73\x8b\x8b\xf3\x4b\x7b\xb0\x90\xd6\x08\x9d"
      "\x7f\x9b\xd1\x07\xbc\x3d\xb4\xa9\x9f\x8a\xfa\x99\xf6\x4e\xef\x57\x3d\xd9"
      "\x47\xbf\x19\x7b\x7a\x9f\x68\xa1\x7f\x20\x4d\x6e\x75\x44\xfd\x3e\xc9\x16"
      "\xe3\xb4\xc7\x11\x7c\x27\xc9\xce\x4e\x71\x74\xb4\xce\x99\xd8\x85\x5d\x9e"
      "\xcc\x90\xa6\xf3\xab\xcf\x74\x92\xd6\x6a\x3c\x49\xae\xee\x91\x1f\xb8\x03"
      "\x76\xc2\xc9\xe5\x6b\x6f\x9e\xbc\xf1\xf6\x3b\x5f\x5a\xb8\x36\xf7\xfa\xfc"
      "\xeb\xf3\xd7\x4f\x9d\x39\xfd\xea\xe9\xee\x97\x67\x6f\x9d\xbc\xbc\xb0\x38"
      "\x3f\x53\x3f\x8e\x3b\x4a\x60\x27\x6c\x7c\x5f\x0a\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\xec\x7d\xbb\xf1\x57\x16\x43\xa6\x2d\x7a\x63\xd8\x57\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\xe0\xff\xd3\xb9\xd7\xb2\xbf\x97\x22\xb3\x33\x27\x66\xca\xfa\xdd\x3b"
      "\xdd\xc5\x72\xe9\x97\xd7\x7a\x4e\x24\x69\x25\x29\xbe\x97\x14\x1f\x27\x67"
      "\x53\x2f\x99\x1a\x18\xae\x78\xd0\x3c\xaf\xdc\xfb\xf0\x17\x2f\xbd\xf7\x41"
      "\x77\x6d\xac\x89\x7e\xff\xd6\x86\xed\xfe\xf0\xaf\x95\x95\x6d\xee\x45\xaf"
      "\x59\x32\x9d\x64\x5f\xb3\x7e\xb8\xc9\x91\xc6\xbb\x38\x30\x5e\x6f\x9b\x81"
      "\xd5\x8a\xd5\x3d\x2c\x13\x76\xac\x9f\x38\x18\xb7\xff\x05\x00\x00\xff\xff"
      "\xd2\x4a\x04\x6e",
      1714);
  syz_mount_image(/*fs=*/0x200000000140, /*dir=*/0x200000000980, /*flags=*/0,
                  /*opts=*/0x2000000001c0, /*chdir=*/3, /*size=*/0x6b2,
                  /*img=*/0x200000000280);
  memcpy((void*)0x200000000900, ".\000", 2);
  res = syscall(__NR_openat, /*fd=*/0xffffff9c, /*file=*/0x200000000900ul,
                /*flags=*/0, /*mode=*/0);
  if (res != -1)
    r[0] = res;
  memcpy((void*)0x200000000180, "./bus\000", 6);
  syscall(__NR_mkdirat, /*fd=*/r[0], /*path=*/0x200000000180ul, /*mode=*/0ul);
  memcpy((void*)0x200000000380, "./file0\000", 8);
  memcpy((void*)0x200000000200, "./bus/file0\000", 12);
  syscall(__NR_renameat2, /*oldfd=*/r[0], /*old=*/0x200000000380ul,
          /*newfd=*/r[0], /*new=*/0x200000000200ul,
          /*flags=RENAME_NOREPLACE*/ 1ul);
}
int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffffffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200000000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200001000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  const char* reason;
  (void)reason;
  loop();
  return 0;
}
