// https://syzkaller.appspot.com/bug?id=7349616606afa3c986c377792f7ccbf9daae1142
// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <dirent.h>
#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/prctl.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

#ifndef __NR_bpf
#define __NR_bpf 321
#endif

static unsigned long long procid;

static void sleep_ms(uint64_t ms)
{
  usleep(ms * 1000);
}

static uint64_t current_time_ms(void)
{
  struct timespec ts;
  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    exit(1);
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

#define BITMASK(bf_off, bf_len) (((1ull << (bf_len)) - 1) << (bf_off))
#define STORE_BY_BITMASK(type, htobe, addr, val, bf_off, bf_len)               \
  *(type*)(addr) =                                                             \
      htobe((htobe(*(type*)(addr)) & ~BITMASK((bf_off), (bf_len))) |           \
            (((type)(val) << (bf_off)) & BITMASK((bf_off), (bf_len))))

static bool write_file(const char* file, const char* what, ...)
{
  char buf[1024];
  va_list args;
  va_start(args, what);
  vsnprintf(buf, sizeof(buf), what, args);
  va_end(args);
  buf[sizeof(buf) - 1] = 0;
  int len = strlen(buf);
  int fd = open(file, O_WRONLY | O_CLOEXEC);
  if (fd == -1)
    return false;
  if (write(fd, buf, len) != len) {
    int err = errno;
    close(fd);
    errno = err;
    return false;
  }
  close(fd);
  return true;
}

static long syz_open_dev(volatile long a0, volatile long a1, volatile long a2)
{
  if (a0 == 0xc || a0 == 0xb) {
    char buf[128];
    sprintf(buf, "/dev/%s/%d:%d", a0 == 0xc ? "char" : "block", (uint8_t)a1,
            (uint8_t)a2);
    return open(buf, O_RDWR, 0);
  } else {
    unsigned long nb = a1;
    char buf[1024];
    char* hash;
    strncpy(buf, (char*)a0, sizeof(buf) - 1);
    buf[sizeof(buf) - 1] = 0;
    while ((hash = strchr(buf, '#'))) {
      *hash = '0' + (char)(nb % 10);
      nb /= 10;
    }
    return open(buf, a2 & ~O_CREAT, 0);
  }
}

static void kill_and_wait(int pid, int* status)
{
  kill(-pid, SIGKILL);
  kill(pid, SIGKILL);
  for (int i = 0; i < 100; i++) {
    if (waitpid(-1, status, WNOHANG | __WALL) == pid)
      return;
    usleep(1000);
  }
  DIR* dir = opendir("/sys/fs/fuse/connections");
  if (dir) {
    for (;;) {
      struct dirent* ent = readdir(dir);
      if (!ent)
        break;
      if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0)
        continue;
      char abort[300];
      snprintf(abort, sizeof(abort), "/sys/fs/fuse/connections/%s/abort",
               ent->d_name);
      int fd = open(abort, O_WRONLY);
      if (fd == -1) {
        continue;
      }
      if (write(fd, abort, 1) < 0) {
      }
      close(fd);
    }
    closedir(dir);
  } else {
  }
  while (waitpid(-1, status, __WALL) != pid) {
  }
}

static void setup_test()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  setpgrp();
  write_file("/proc/self/oom_score_adj", "1000");
}

static void execute_one(void);

#define WAIT_FLAGS __WALL

static void loop(void)
{
  int iter = 0;
  for (;; iter++) {
    int pid = fork();
    if (pid < 0)
      exit(1);
    if (pid == 0) {
      setup_test();
      execute_one();
      exit(0);
    }
    int status = 0;
    uint64_t start = current_time_ms();
    for (;;) {
      sleep_ms(10);
      if (waitpid(-1, &status, WNOHANG | WAIT_FLAGS) == pid)
        break;
      if (current_time_ms() - start < 5000)
        continue;
      kill_and_wait(pid, &status);
      break;
    }
  }
}

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};

void execute_one(void)
{
  intptr_t res = 0;
  if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {
  }
  //  prlimit64 arguments: [
  //    pid: pid (resource)
  //    res: rlimit_type = 0xe (8 bytes)
  //    new: ptr[in, rlimit] {
  //      rlimit {
  //        soft: intptr = 0x8 (8 bytes)
  //        hard: intptr = 0x8b (8 bytes)
  //      }
  //    }
  //    old: nil
  //  ]
  *(uint64_t*)0x200000000140 = 8;
  *(uint64_t*)0x200000000148 = 0x8b;
  syscall(__NR_prlimit64, /*pid=*/0, /*res=RLIMIT_RTPRIO*/ 0xeul,
          /*new=*/0x200000000140ul, /*old=*/0ul);
  //  sched_setscheduler arguments: [
  //    pid: pid (resource)
  //    policy: sched_policy = 0x2 (8 bytes)
  //    prio: ptr[in, int32] {
  //      int32 = 0x4 (4 bytes)
  //    }
  //  ]
  *(uint32_t*)0x200000000180 = 4;
  syscall(__NR_sched_setscheduler, /*pid=*/0, /*policy=SCHED_RR*/ 2ul,
          /*prio=*/0x200000000180ul);
  //  prctl$PR_SCHED_CORE arguments: [
  //    option: const = 0x3e (8 bytes)
  //    cmd: intptr = 0x1 (8 bytes)
  //    pid: pid (resource)
  //    type: pid_type = 0x2 (8 bytes)
  //    uaddr: nil
  //  ]
  syscall(__NR_prctl, /*option=*/0x3eul, /*cmd=*/1ul, /*pid=*/0,
          /*type=PIDTYPE_PGID*/ 2ul, /*uaddr=*/0ul);
  //  bpf$MAP_CREATE_CONST_STR arguments: [
  //    cmd: const = 0x0 (8 bytes)
  //    arg: ptr[in, bpf_map_create_arg_t[const[BPF_MAP_TYPE_ARRAY, int32],
  //    const[4, int32], const[8, int32], const[1, int32],
  //    const[BPF_F_RDONLY_PROG, int32], const[0, int64]]] {
  //      bpf_map_create_arg_t[const[BPF_MAP_TYPE_ARRAY, int32], const[4,
  //      int32], const[8, int32], const[1, int32], const[BPF_F_RDONLY_PROG,
  //      int32], const[0, int64]] {
  //        type: const = 0x2 (4 bytes)
  //        ksize: const = 0x4 (4 bytes)
  //        vsize: const = 0x8 (4 bytes)
  //        max: const = 0x1 (4 bytes)
  //        flags: const = 0x80 (4 bytes)
  //        inner: fd_bpf_map (resource)
  //        node: int32 = 0x0 (4 bytes)
  //        map_name: buffer: {00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00}
  //        (length 0x10) map_ifindex: ifindex (resource) btf_fd: fd_btf
  //        (resource) btf_key_type_id: int32 = 0x0 (4 bytes) btf_value_type_id:
  //        int32 = 0x0 (4 bytes) btf_vmlinux_type_id: int32 = 0x0 (4 bytes)
  //        map_extra: const = 0x0 (8 bytes)
  //        value_type_btf_obj_fd: union
  //        _bpf_map_create_arg_t[const[BPF_MAP_TYPE_ARRAY, int32], const[4,
  //        int32], const[8, int32], const[1, int32], const[BPF_F_RDONLY_PROG,
  //        int32], const[0, int64]]_value_type_btf_obj_fd_wrapper {
  //          void: buffer: {} (length 0x0)
  //        }
  //        pad1: union _bpf_map_create_arg_t[const[BPF_MAP_TYPE_ARRAY, int32],
  //        const[4, int32], const[8, int32], const[1, int32],
  //        const[BPF_F_RDONLY_PROG, int32], const[0, int64]]_pad1_wrapper {
  //          value: const = 0x0 (4 bytes)
  //        }
  //        map_token_fd: union _bpf_map_create_arg_t[const[BPF_MAP_TYPE_ARRAY,
  //        int32], const[4, int32], const[8, int32], const[1, int32],
  //        const[BPF_F_RDONLY_PROG, int32], const[0,
  //        int64]]_map_token_fd_wrapper {
  //          void: buffer: {} (length 0x0)
  //        }
  //        pad2: union _bpf_map_create_arg_t[const[BPF_MAP_TYPE_ARRAY, int32],
  //        const[4, int32], const[8, int32], const[1, int32],
  //        const[BPF_F_RDONLY_PROG, int32], const[0, int64]]_pad2_wrapper {
  //          value: const = 0x0 (4 bytes)
  //        }
  //      }
  //    }
  //    size: len = 0x50 (8 bytes)
  //  ]
  //  returns fd_bpf_const_str_map
  *(uint32_t*)0x200000000500 = 2;
  *(uint32_t*)0x200000000504 = 4;
  *(uint32_t*)0x200000000508 = 8;
  *(uint32_t*)0x20000000050c = 1;
  *(uint32_t*)0x200000000510 = 0x80;
  *(uint32_t*)0x200000000514 = 0;
  *(uint32_t*)0x200000000518 = 0;
  memset((void*)0x20000000051c, 0, 16);
  *(uint32_t*)0x20000000052c = 0;
  *(uint32_t*)0x200000000530 = 0;
  *(uint32_t*)0x200000000534 = 0;
  *(uint32_t*)0x200000000538 = 0;
  *(uint32_t*)0x20000000053c = 0;
  *(uint64_t*)0x200000000540 = 0;
  *(uint32_t*)0x200000000548 = 0;
  *(uint32_t*)0x20000000054c = 0;
  res =
      syscall(__NR_bpf, /*cmd=*/0ul, /*arg=*/0x200000000500ul, /*size=*/0x50ul);
  if (res != -1)
    r[0] = res;
  //  bpf$BPF_MAP_CONST_STR_FREEZE arguments: [
  //    cmd: const = 0x16 (8 bytes)
  //    arg: ptr[inout, bpf_map_const_str_freeze] {
  //      bpf_map_const_str_freeze {
  //        in: fd_bpf_const_str (resource)
  //        out: bpf_frozen_const_str (resource)
  //      }
  //    }
  //    size: len = 0x4 (8 bytes)
  //  ]
  *(uint32_t*)0x200000000080 = r[0];
  syscall(__NR_bpf, /*cmd=*/0x16ul, /*arg=*/0x200000000080ul, /*size=*/4ul);
  //  bpf$BPF_PROG_RAW_TRACEPOINT_LOAD arguments: [
  //    cmd: const = 0x5 (8 bytes)
  //    arg: ptr[in, bpf_prog_t[flags[bpf_raw_tracepoint_prog_types, int32],
  //    const[0, int32], const[0, int32], const[0, int32]]] {
  //      bpf_prog_t[flags[bpf_raw_tracepoint_prog_types, int32], const[0,
  //      int32], const[0, int32], const[0, int32]] {
  //        type: bpf_raw_tracepoint_prog_types = 0x3 (4 bytes)
  //        ninsn: bytesize8 = 0x11 (4 bytes)
  //        insns: ptr[in, bpf_instructions] {
  //          union bpf_instructions {
  //            framed: bpf_framed_program {
  //              initr0: bpf_insn_init_r0 {
  //                code: const = 0x18 (1 bytes)
  //                dst: const = 0x2 (0 bytes)
  //                src: const = 0x0 (1 bytes)
  //                off: const = 0x0 (2 bytes)
  //                imm: int32 = 0x0 (4 bytes)
  //                code2: const = 0x0 (1 bytes)
  //                regs2: const = 0x0 (1 bytes)
  //                off2: const = 0x0 (2 bytes)
  //                imm2: int32 = 0x7ed1 (4 bytes)
  //              }
  //              body: array[bpf_insn] {
  //                union bpf_insn {
  //                  call: bpf_insn_call_helper_t[int32[0:__BPF_FUNC_MAX_ID]] {
  //                    code: const = 0x85 (1 bytes)
  //                    regs: const = 0x0 (1 bytes)
  //                    off: const = 0x0 (2 bytes)
  //                    func: int32 = 0x30 (4 bytes)
  //                  }
  //                }
  //                union bpf_insn {
  //                  snprintf: bpf_insn_snprintf {
  //                    insn1: bpf_insn_alu_t[BPF_ALU64, BPF_K0, BPF_MOV0,
  //                    const[BPF_REG_8, int8:4], const[0, int8:4], const[0,
  //                    int16], const[0, int32]] {
  //                      code_class: int8 = 0x7 (0 bytes)
  //                      code_s: int8 = 0x0 (0 bytes)
  //                      code_op: int8 = 0xb (1 bytes)
  //                      dst: const = 0x8 (0 bytes)
  //                      src: const = 0x0 (1 bytes)
  //                      off: const = 0x0 (2 bytes)
  //                      imm: const = 0x0 (4 bytes)
  //                    }
  //                    insn2: bpf_insn_ldst_t[BPF_STX, BPF_DW0, BPF_MEM0,
  //                    const[BPF_REG_10, int8:4], const[BPF_REG_8, int8:4],
  //                    const[-8, int16], const[0, int32]] {
  //                      code_class: int8 = 0x3 (0 bytes)
  //                      code_size: int8 = 0x3 (0 bytes)
  //                      code_mode: int8 = 0x3 (1 bytes)
  //                      dst: const = 0xa (0 bytes)
  //                      src: const = 0x8 (1 bytes)
  //                      off: const = 0xfff8 (2 bytes)
  //                      imm: const = 0x0 (4 bytes)
  //                    }
  //                    insn3: bpf_insn_alu_t[BPF_ALU64, BPF_K0, BPF_MOV0,
  //                    const[BPF_REG_8, int8:4], const[0, int8:4], const[0,
  //                    int16], int32] {
  //                      code_class: int8 = 0x7 (0 bytes)
  //                      code_s: int8 = 0x0 (0 bytes)
  //                      code_op: int8 = 0xb (1 bytes)
  //                      dst: const = 0x8 (0 bytes)
  //                      src: const = 0x0 (1 bytes)
  //                      off: const = 0x0 (2 bytes)
  //                      imm: int32 = 0xffffffff (4 bytes)
  //                    }
  //                    insn4: bpf_insn_ldst_t[BPF_STX, BPF_DW0, BPF_MEM0,
  //                    const[BPF_REG_10, int8:4], const[BPF_REG_8, int8:4],
  //                    const[-16, int16], const[0, int32]] {
  //                      code_class: int8 = 0x3 (0 bytes)
  //                      code_size: int8 = 0x3 (0 bytes)
  //                      code_mode: int8 = 0x3 (1 bytes)
  //                      dst: const = 0xa (0 bytes)
  //                      src: const = 0x8 (1 bytes)
  //                      off: const = 0xfff0 (2 bytes)
  //                      imm: const = 0x0 (4 bytes)
  //                    }
  //                    insn5: bpf_insn_alu_t[BPF_ALU64, BPF_X0, BPF_MOV0,
  //                    const[BPF_REG_1, int8:4], const[BPF_REG_10, int8:4],
  //                    const[0, int16], const[0, int32]] {
  //                      code_class: int8 = 0x7 (0 bytes)
  //                      code_s: int8 = 0x1 (0 bytes)
  //                      code_op: int8 = 0xb (1 bytes)
  //                      dst: const = 0x1 (0 bytes)
  //                      src: const = 0xa (1 bytes)
  //                      off: const = 0x0 (2 bytes)
  //                      imm: const = 0x0 (4 bytes)
  //                    }
  //                    insn6: bpf_insn_alu_t[BPF_ALU64, BPF_K0, BPF_ADD0,
  //                    const[BPF_REG_1, int8:4], const[0, int8:4], const[0,
  //                    int16], const[-8, int32]] {
  //                      code_class: int8 = 0x7 (0 bytes)
  //                      code_s: int8 = 0x0 (0 bytes)
  //                      code_op: int8 = 0x0 (1 bytes)
  //                      dst: const = 0x1 (0 bytes)
  //                      src: const = 0x0 (1 bytes)
  //                      off: const = 0x0 (2 bytes)
  //                      imm: const = 0xfffffff8 (4 bytes)
  //                    }
  //                    insn7: bpf_insn_alu_t[BPF_ALU64, BPF_X0, BPF_MOV0,
  //                    const[BPF_REG_4, int8:4], const[BPF_REG_10, int8:4],
  //                    const[0, int16], const[0, int32]] {
  //                      code_class: int8 = 0x7 (0 bytes)
  //                      code_s: int8 = 0x1 (0 bytes)
  //                      code_op: int8 = 0xb (1 bytes)
  //                      dst: const = 0x4 (0 bytes)
  //                      src: const = 0xa (1 bytes)
  //                      off: const = 0x0 (2 bytes)
  //                      imm: const = 0x0 (4 bytes)
  //                    }
  //                    insn8: bpf_insn_alu_t[BPF_ALU64, BPF_K0, BPF_ADD0,
  //                    const[BPF_REG_4, int8:4], const[0, int8:4], const[0,
  //                    int16], const[-16, int32]] {
  //                      code_class: int8 = 0x7 (0 bytes)
  //                      code_s: int8 = 0x0 (0 bytes)
  //                      code_op: int8 = 0x0 (1 bytes)
  //                      dst: const = 0x4 (0 bytes)
  //                      src: const = 0x0 (1 bytes)
  //                      off: const = 0x0 (2 bytes)
  //                      imm: const = 0xfffffff0 (4 bytes)
  //                    }
  //                    insn9: bpf_insn_alu_t[BPF_ALU64, BPF_K0, BPF_MOV0,
  //                    const[BPF_REG_2, int8:4], const[0, int8:4], const[0,
  //                    int16], const[8, int32]] {
  //                      code_class: int8 = 0x7 (0 bytes)
  //                      code_s: int8 = 0x0 (0 bytes)
  //                      code_op: int8 = 0xb (1 bytes)
  //                      dst: const = 0x2 (0 bytes)
  //                      src: const = 0x0 (1 bytes)
  //                      off: const = 0x0 (2 bytes)
  //                      imm: const = 0x8 (4 bytes)
  //                    }
  //                    insn10: bpf_insn_map_value_t[const[BPF_REG_3, int8:4],
  //                    bpf_frozen_const_str, const[0, int32]] {
  //                      code: const = 0x18 (1 bytes)
  //                      dst: const = 0x3 (0 bytes)
  //                      src: const = 0x2 (1 bytes)
  //                      off: const = 0x0 (2 bytes)
  //                      imm: bpf_frozen_const_str (resource)
  //                      code2: const = 0x0 (1 bytes)
  //                      regs2: const = 0x0 (1 bytes)
  //                      off2: const = 0x0 (2 bytes)
  //                      imm2: const = 0x0 (4 bytes)
  //                    }
  //                    insn11: bpf_insn_alu_t[BPF_ALU64, BPF_K0, BPF_MOV0,
  //                    const[BPF_REG_5, int8:4], const[0, int8:4], const[0,
  //                    int16], const[8, int32]] {
  //                      code_class: int8 = 0x7 (0 bytes)
  //                      code_s: int8 = 0x0 (0 bytes)
  //                      code_op: int8 = 0xb (1 bytes)
  //                      dst: const = 0x5 (0 bytes)
  //                      src: const = 0x0 (1 bytes)
  //                      off: const = 0x0 (2 bytes)
  //                      imm: const = 0x8 (4 bytes)
  //                    }
  //                    insn12: bpf_insn_call_helper_t[const[BPF_FUNC_snprintf,
  //                    int32]] {
  //                      code: const = 0x85 (1 bytes)
  //                      regs: const = 0x0 (1 bytes)
  //                      off: const = 0x0 (2 bytes)
  //                      func: const = 0xa5 (4 bytes)
  //                    }
  //                  }
  //                }
  //              }
  //              exit: bpf_insn_exit {
  //                code: const = 0x95 (1 bytes)
  //                regs: const = 0x0 (1 bytes)
  //                off: const = 0x0 (2 bytes)
  //                imm: const = 0x0 (4 bytes)
  //              }
  //            }
  //          }
  //        }
  //        license: ptr[in, buffer] {
  //          buffer: {47 50 4c 00} (length 0x4)
  //        }
  //        loglev: int32 = 0x0 (4 bytes)
  //        logsize: len = 0x0 (4 bytes)
  //        log: nil
  //        kern_version: bpf_kern_version = 0x0 (4 bytes)
  //        flags: bpf_prog_load_flags = 0x0 (4 bytes)
  //        prog_name: buffer: {00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00}
  //        (length 0x10) prog_ifindex: ifindex (resource) expected_attach_type:
  //        const = 0x0 (4 bytes) btf_fd: fd_btf (resource) func_info_rec_size:
  //        const = 0x8 (4 bytes) func_info: nil func_info_cnt: len = 0x0 (4
  //        bytes) line_info_rec_size: const = 0x10 (4 bytes) line_info: nil
  //        line_info_cnt: len = 0x0 (4 bytes)
  //        attach_btf_id: const = 0x0 (4 bytes)
  //        attach_prog_fd: const = 0x0 (4 bytes)
  //        core_relo_cnt: len = 0x0 (4 bytes)
  //        fd_array: nil
  //        core_relos: nil
  //        core_relo_rec_size: const = 0x10 (4 bytes)
  //        log_true_size: int32 = 0x4 (4 bytes)
  //        prog_token_fd: union
  //        _bpf_prog_t[flags[bpf_raw_tracepoint_prog_types, int32], const[0,
  //        int32], const[0, int32], const[0, int32]]_prog_token_fd_wrapper {
  //          void: buffer: {} (length 0x0)
  //        }
  //        pad: union _bpf_prog_t[flags[bpf_raw_tracepoint_prog_types, int32],
  //        const[0, int32], const[0, int32], const[0, int32]]_pad_wrapper {
  //          value: const = 0x0 (4 bytes)
  //        }
  //      }
  //    }
  //    size: len = 0x94 (8 bytes)
  //  ]
  //  returns fd_bpf_prog_raw_tracepoint
  *(uint32_t*)0x200000000140 = 3;
  *(uint32_t*)0x200000000144 = 0x11;
  *(uint64_t*)0x200000000148 = 0x200000000200;
  *(uint8_t*)0x200000000200 = 0x18;
  STORE_BY_BITMASK(uint8_t, , 0x200000000201, 2, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x200000000201, 0, 4, 4);
  *(uint16_t*)0x200000000202 = 0;
  *(uint32_t*)0x200000000204 = 0;
  *(uint8_t*)0x200000000208 = 0;
  *(uint8_t*)0x200000000209 = 0;
  *(uint16_t*)0x20000000020a = 0;
  *(uint32_t*)0x20000000020c = 0x7ed1;
  *(uint8_t*)0x200000000210 = 0x85;
  *(uint8_t*)0x200000000211 = 0;
  *(uint16_t*)0x200000000212 = 0;
  *(uint32_t*)0x200000000214 = 0x30;
  STORE_BY_BITMASK(uint8_t, , 0x200000000218, 7, 0, 3);
  STORE_BY_BITMASK(uint8_t, , 0x200000000218, 0, 3, 1);
  STORE_BY_BITMASK(uint8_t, , 0x200000000218, 0xb, 4, 4);
  STORE_BY_BITMASK(uint8_t, , 0x200000000219, 8, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x200000000219, 0, 4, 4);
  *(uint16_t*)0x20000000021a = 0;
  *(uint32_t*)0x20000000021c = 0;
  STORE_BY_BITMASK(uint8_t, , 0x200000000220, 3, 0, 3);
  STORE_BY_BITMASK(uint8_t, , 0x200000000220, 3, 3, 2);
  STORE_BY_BITMASK(uint8_t, , 0x200000000220, 3, 5, 3);
  STORE_BY_BITMASK(uint8_t, , 0x200000000221, 0xa, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x200000000221, 8, 4, 4);
  *(uint16_t*)0x200000000222 = 0xfff8;
  *(uint32_t*)0x200000000224 = 0;
  STORE_BY_BITMASK(uint8_t, , 0x200000000228, 7, 0, 3);
  STORE_BY_BITMASK(uint8_t, , 0x200000000228, 0, 3, 1);
  STORE_BY_BITMASK(uint8_t, , 0x200000000228, 0xb, 4, 4);
  STORE_BY_BITMASK(uint8_t, , 0x200000000229, 8, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x200000000229, 0, 4, 4);
  *(uint16_t*)0x20000000022a = 0;
  *(uint32_t*)0x20000000022c = -1;
  STORE_BY_BITMASK(uint8_t, , 0x200000000230, 3, 0, 3);
  STORE_BY_BITMASK(uint8_t, , 0x200000000230, 3, 3, 2);
  STORE_BY_BITMASK(uint8_t, , 0x200000000230, 3, 5, 3);
  STORE_BY_BITMASK(uint8_t, , 0x200000000231, 0xa, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x200000000231, 8, 4, 4);
  *(uint16_t*)0x200000000232 = 0xfff0;
  *(uint32_t*)0x200000000234 = 0;
  STORE_BY_BITMASK(uint8_t, , 0x200000000238, 7, 0, 3);
  STORE_BY_BITMASK(uint8_t, , 0x200000000238, 1, 3, 1);
  STORE_BY_BITMASK(uint8_t, , 0x200000000238, 0xb, 4, 4);
  STORE_BY_BITMASK(uint8_t, , 0x200000000239, 1, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x200000000239, 0xa, 4, 4);
  *(uint16_t*)0x20000000023a = 0;
  *(uint32_t*)0x20000000023c = 0;
  STORE_BY_BITMASK(uint8_t, , 0x200000000240, 7, 0, 3);
  STORE_BY_BITMASK(uint8_t, , 0x200000000240, 0, 3, 1);
  STORE_BY_BITMASK(uint8_t, , 0x200000000240, 0, 4, 4);
  STORE_BY_BITMASK(uint8_t, , 0x200000000241, 1, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x200000000241, 0, 4, 4);
  *(uint16_t*)0x200000000242 = 0;
  *(uint32_t*)0x200000000244 = 0xfffffff8;
  STORE_BY_BITMASK(uint8_t, , 0x200000000248, 7, 0, 3);
  STORE_BY_BITMASK(uint8_t, , 0x200000000248, 1, 3, 1);
  STORE_BY_BITMASK(uint8_t, , 0x200000000248, 0xb, 4, 4);
  STORE_BY_BITMASK(uint8_t, , 0x200000000249, 4, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x200000000249, 0xa, 4, 4);
  *(uint16_t*)0x20000000024a = 0;
  *(uint32_t*)0x20000000024c = 0;
  STORE_BY_BITMASK(uint8_t, , 0x200000000250, 7, 0, 3);
  STORE_BY_BITMASK(uint8_t, , 0x200000000250, 0, 3, 1);
  STORE_BY_BITMASK(uint8_t, , 0x200000000250, 0, 4, 4);
  STORE_BY_BITMASK(uint8_t, , 0x200000000251, 4, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x200000000251, 0, 4, 4);
  *(uint16_t*)0x200000000252 = 0;
  *(uint32_t*)0x200000000254 = 0xfffffff0;
  STORE_BY_BITMASK(uint8_t, , 0x200000000258, 7, 0, 3);
  STORE_BY_BITMASK(uint8_t, , 0x200000000258, 0, 3, 1);
  STORE_BY_BITMASK(uint8_t, , 0x200000000258, 0xb, 4, 4);
  STORE_BY_BITMASK(uint8_t, , 0x200000000259, 2, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x200000000259, 0, 4, 4);
  *(uint16_t*)0x20000000025a = 0;
  *(uint32_t*)0x20000000025c = 8;
  *(uint8_t*)0x200000000260 = 0x18;
  STORE_BY_BITMASK(uint8_t, , 0x200000000261, 3, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x200000000261, 2, 4, 4);
  *(uint16_t*)0x200000000262 = 0;
  *(uint32_t*)0x200000000264 = r[0];
  *(uint8_t*)0x200000000268 = 0;
  *(uint8_t*)0x200000000269 = 0;
  *(uint16_t*)0x20000000026a = 0;
  *(uint32_t*)0x20000000026c = 0;
  STORE_BY_BITMASK(uint8_t, , 0x200000000270, 7, 0, 3);
  STORE_BY_BITMASK(uint8_t, , 0x200000000270, 0, 3, 1);
  STORE_BY_BITMASK(uint8_t, , 0x200000000270, 0xb, 4, 4);
  STORE_BY_BITMASK(uint8_t, , 0x200000000271, 5, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x200000000271, 0, 4, 4);
  *(uint16_t*)0x200000000272 = 0;
  *(uint32_t*)0x200000000274 = 8;
  *(uint8_t*)0x200000000278 = 0x85;
  *(uint8_t*)0x200000000279 = 0;
  *(uint16_t*)0x20000000027a = 0;
  *(uint32_t*)0x20000000027c = 0xa5;
  *(uint8_t*)0x200000000280 = 0x95;
  *(uint8_t*)0x200000000281 = 0;
  *(uint16_t*)0x200000000282 = 0;
  *(uint32_t*)0x200000000284 = 0;
  *(uint64_t*)0x200000000150 = 0x200000000080;
  memcpy((void*)0x200000000080, "GPL\000", 4);
  *(uint32_t*)0x200000000158 = 0;
  *(uint32_t*)0x20000000015c = 0;
  *(uint64_t*)0x200000000160 = 0;
  *(uint32_t*)0x200000000168 = 0;
  *(uint32_t*)0x20000000016c = 0;
  memset((void*)0x200000000170, 0, 16);
  *(uint32_t*)0x200000000180 = 0;
  *(uint32_t*)0x200000000184 = 0;
  *(uint32_t*)0x200000000188 = -1;
  *(uint32_t*)0x20000000018c = 8;
  *(uint64_t*)0x200000000190 = 0;
  *(uint32_t*)0x200000000198 = 0;
  *(uint32_t*)0x20000000019c = 0x10;
  *(uint64_t*)0x2000000001a0 = 0;
  *(uint32_t*)0x2000000001a8 = 0;
  *(uint32_t*)0x2000000001ac = 0;
  *(uint32_t*)0x2000000001b0 = 0;
  *(uint32_t*)0x2000000001b4 = 0;
  *(uint64_t*)0x2000000001b8 = 0;
  *(uint64_t*)0x2000000001c0 = 0;
  *(uint32_t*)0x2000000001c8 = 0x10;
  *(uint32_t*)0x2000000001cc = 4;
  *(uint32_t*)0x2000000001d0 = 0;
  res =
      syscall(__NR_bpf, /*cmd=*/5ul, /*arg=*/0x200000000140ul, /*size=*/0x94ul);
  if (res != -1)
    r[1] = res;
  //  bpf$BPF_PROG_TEST_RUN arguments: [
  //    cmd: const = 0xa (8 bytes)
  //    arg: ptr[in, bpf_test_prog_arg] {
  //      bpf_test_prog_arg {
  //        prog: fd_bpf_prog (resource)
  //        retval: const = 0x0 (4 bytes)
  //        insizedata: len = 0xe (4 bytes)
  //        outsizedata: len = 0x0 (4 bytes)
  //        indata: ptr[in, buffer] {
  //          buffer: {b3 47 15 ec d0 45 50 d3 ab c8 9b 6f 7b ec} (length 0xe)
  //        }
  //        outdata: nil
  //        repeat: int32 = 0xfffdfffc (4 bytes)
  //        dur: const = 0x0 (4 bytes)
  //        insizectx: len = 0x0 (4 bytes)
  //        outsizectx: len = 0x0 (4 bytes)
  //        inctx: nil
  //        outctx: nil
  //        flags: bpf_prog_test_run_flags = 0x0 (4 bytes)
  //        cpu: const = 0x0 (4 bytes)
  //        batch_size: int32 = 0x0 (4 bytes)
  //        pad = 0x0 (4 bytes)
  //      }
  //    }
  //    size: len = 0x50 (8 bytes)
  //  ]
  *(uint32_t*)0x200000000480 = r[1];
  *(uint32_t*)0x200000000484 = 0;
  *(uint32_t*)0x200000000488 = 0xe;
  *(uint32_t*)0x20000000048c = 0;
  *(uint64_t*)0x200000000490 = 0x200000000100;
  memcpy((void*)0x200000000100,
         "\xb3\x47\x15\xec\xd0\x45\x50\xd3\xab\xc8\x9b\x6f\x7b\xec", 14);
  *(uint64_t*)0x200000000498 = 0;
  *(uint32_t*)0x2000000004a0 = 0xfffdfffc;
  *(uint32_t*)0x2000000004a4 = 0;
  *(uint32_t*)0x2000000004a8 = 0;
  *(uint32_t*)0x2000000004ac = 0;
  *(uint64_t*)0x2000000004b0 = 0;
  *(uint64_t*)0x2000000004b8 = 0;
  *(uint32_t*)0x2000000004c0 = 0;
  *(uint32_t*)0x2000000004c4 = 0;
  *(uint32_t*)0x2000000004c8 = 0;
  syscall(__NR_bpf, /*cmd=*/0xaul, /*arg=*/0x200000000480ul, /*size=*/0x50ul);
  //  syz_open_dev$evdev arguments: [
  //    dev: ptr[in, buffer] {
  //      buffer: {2f 64 65 76 2f 69 6e 70 75 74 2f 65 76 65 6e 74 23 00}
  //      (length 0x12)
  //    }
  //    id: intptr = 0x20000 (8 bytes)
  //    flags: open_flags = 0x0 (8 bytes)
  //  ]
  //  returns fd_evdev
  memcpy((void*)0x200000000240, "/dev/input/event#\000", 18);
  syz_open_dev(/*dev=*/0x200000000240, /*id=*/0x20000, /*flags=*/0);
}
int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffffffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200000000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200001000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  const char* reason;
  (void)reason;
  for (procid = 0; procid < 5; procid++) {
    if (fork() == 0) {
      loop();
    }
  }
  sleep(1000000);
  return 0;
}
