// https://syzkaller.appspot.com/bug?id=7635d5fc7d78f9c7c2017087a60aa79da32626e2
// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x20000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x21000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  const char* reason;
  (void)reason;
  intptr_t res = 0;
  if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {
  }
  memcpy((void*)0x20000300, "./file0\000", 8);
  syscall(__NR_mkdir, /*path=*/0x20000300ul, /*mode=*/0ul);
  memcpy((void*)0x20002080, "/dev/fuse\000", 10);
  res = syscall(__NR_openat, /*fd=*/0xffffffffffffff9cul, /*file=*/0x20002080ul,
                /*flags=*/0x42, /*mode=*/0);
  if (res != -1)
    r[0] = res;
  memcpy((void*)0x200042c0, "./file0\000", 8);
  memcpy((void*)0x20000100, "fuse\000", 5);
  memcpy((void*)0x20000200, "fd", 2);
  *(uint8_t*)0x20000202 = 0x3d;
  sprintf((char*)0x20000203, "0x%016llx", (long long)r[0]);
  *(uint8_t*)0x20000215 = 0x2c;
  memcpy((void*)0x20000216, "rootmode", 8);
  *(uint8_t*)0x2000021e = 0x3d;
  sprintf((char*)0x2000021f, "%023llo", (long long)0x4000);
  *(uint8_t*)0x20000236 = 0x2c;
  memcpy((void*)0x20000237, "user_id", 7);
  *(uint8_t*)0x2000023e = 0x3d;
  sprintf((char*)0x2000023f, "%020llu", (long long)0);
  *(uint8_t*)0x20000253 = 0x2c;
  memcpy((void*)0x20000254, "group_id", 8);
  *(uint8_t*)0x2000025c = 0x3d;
  sprintf((char*)0x2000025d, "%020llu", (long long)0);
  *(uint8_t*)0x20000271 = 0x2c;
  *(uint8_t*)0x20000272 = 0;
  syscall(__NR_mount, /*src=*/0ul, /*dst=*/0x200042c0ul, /*type=*/0x20000100ul,
          /*flags=*/0ul, /*opts=*/0x20000200ul);
  *(uint32_t*)0x20001f80 = 0x2a;
  *(uint32_t*)0x20001f84 = 4;
  *(uint64_t*)0x20001f88 = 0;
  *(uint64_t*)0x20001f90 = 1;
  *(uint64_t*)0x20001f98 = 0xffffffff;
  *(uint32_t*)0x20001fa0 = 2;
  *(uint32_t*)0x20001fa4 = 0;
  *(uint8_t*)0x20001fa8 = 0;
  *(uint8_t*)0x20001fa9 = 0;
  syscall(__NR_write, /*fd=*/r[0], /*arg=*/0x20001f80ul, /*len=*/0x2aul);
  return 0;
}
