// https://syzkaller.appspot.com/bug?id=932aa11538a56e45b2c3a97b0b3aeb3bd4027c03
// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <arpa/inet.h>
#include <dirent.h>
#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <net/if.h>
#include <netinet/in.h>
#include <setjmp.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <sys/mount.h>
#include <sys/prctl.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

#include <linux/genetlink.h>
#include <linux/if_addr.h>
#include <linux/if_link.h>
#include <linux/in6.h>
#include <linux/loop.h>
#include <linux/neighbour.h>
#include <linux/net.h>
#include <linux/netlink.h>
#include <linux/rtnetlink.h>
#include <linux/veth.h>

#ifndef __NR_memfd_create
#define __NR_memfd_create 319
#endif

static unsigned long long procid;

static void sleep_ms(uint64_t ms)
{
  usleep(ms * 1000);
}

static uint64_t current_time_ms(void)
{
  struct timespec ts;
  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    exit(1);
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

static void use_temporary_dir(void)
{
  char tmpdir_template[] = "./syzkaller.XXXXXX";
  char* tmpdir = mkdtemp(tmpdir_template);
  if (!tmpdir)
    exit(1);
  if (chmod(tmpdir, 0777))
    exit(1);
  if (chdir(tmpdir))
    exit(1);
}

static bool write_file(const char* file, const char* what, ...)
{
  char buf[1024];
  va_list args;
  va_start(args, what);
  vsnprintf(buf, sizeof(buf), what, args);
  va_end(args);
  buf[sizeof(buf) - 1] = 0;
  int len = strlen(buf);
  int fd = open(file, O_WRONLY | O_CLOEXEC);
  if (fd == -1)
    return false;
  if (write(fd, buf, len) != len) {
    int err = errno;
    close(fd);
    errno = err;
    return false;
  }
  close(fd);
  return true;
}

struct nlmsg {
  char* pos;
  int nesting;
  struct nlattr* nested[8];
  char buf[4096];
};

static void netlink_init(struct nlmsg* nlmsg, int typ, int flags,
                         const void* data, int size)
{
  memset(nlmsg, 0, sizeof(*nlmsg));
  struct nlmsghdr* hdr = (struct nlmsghdr*)nlmsg->buf;
  hdr->nlmsg_type = typ;
  hdr->nlmsg_flags = NLM_F_REQUEST | NLM_F_ACK | flags;
  memcpy(hdr + 1, data, size);
  nlmsg->pos = (char*)(hdr + 1) + NLMSG_ALIGN(size);
}

static void netlink_attr(struct nlmsg* nlmsg, int typ, const void* data,
                         int size)
{
  struct nlattr* attr = (struct nlattr*)nlmsg->pos;
  attr->nla_len = sizeof(*attr) + size;
  attr->nla_type = typ;
  if (size > 0)
    memcpy(attr + 1, data, size);
  nlmsg->pos += NLMSG_ALIGN(attr->nla_len);
}

static void netlink_nest(struct nlmsg* nlmsg, int typ)
{
  struct nlattr* attr = (struct nlattr*)nlmsg->pos;
  attr->nla_type = typ;
  nlmsg->pos += sizeof(*attr);
  nlmsg->nested[nlmsg->nesting++] = attr;
}

static void netlink_done(struct nlmsg* nlmsg)
{
  struct nlattr* attr = nlmsg->nested[--nlmsg->nesting];
  attr->nla_len = nlmsg->pos - (char*)attr;
}

static int netlink_send_ext(struct nlmsg* nlmsg, int sock, uint16_t reply_type,
                            int* reply_len, bool dofail)
{
  if (nlmsg->pos > nlmsg->buf + sizeof(nlmsg->buf) || nlmsg->nesting)
    exit(1);
  struct nlmsghdr* hdr = (struct nlmsghdr*)nlmsg->buf;
  hdr->nlmsg_len = nlmsg->pos - nlmsg->buf;
  struct sockaddr_nl addr;
  memset(&addr, 0, sizeof(addr));
  addr.nl_family = AF_NETLINK;
  ssize_t n = sendto(sock, nlmsg->buf, hdr->nlmsg_len, 0,
                     (struct sockaddr*)&addr, sizeof(addr));
  if (n != (ssize_t)hdr->nlmsg_len) {
    if (dofail)
      exit(1);
    return -1;
  }
  n = recv(sock, nlmsg->buf, sizeof(nlmsg->buf), 0);
  if (reply_len)
    *reply_len = 0;
  if (n < 0) {
    if (dofail)
      exit(1);
    return -1;
  }
  if (n < (ssize_t)sizeof(struct nlmsghdr)) {
    errno = EINVAL;
    if (dofail)
      exit(1);
    return -1;
  }
  if (hdr->nlmsg_type == NLMSG_DONE)
    return 0;
  if (reply_len && hdr->nlmsg_type == reply_type) {
    *reply_len = n;
    return 0;
  }
  if (n < (ssize_t)(sizeof(struct nlmsghdr) + sizeof(struct nlmsgerr))) {
    errno = EINVAL;
    if (dofail)
      exit(1);
    return -1;
  }
  if (hdr->nlmsg_type != NLMSG_ERROR) {
    errno = EINVAL;
    if (dofail)
      exit(1);
    return -1;
  }
  errno = -((struct nlmsgerr*)(hdr + 1))->error;
  return -errno;
}

static int netlink_send(struct nlmsg* nlmsg, int sock)
{
  return netlink_send_ext(nlmsg, sock, 0, NULL, true);
}

static int netlink_query_family_id(struct nlmsg* nlmsg, int sock,
                                   const char* family_name, bool dofail)
{
  struct genlmsghdr genlhdr;
  memset(&genlhdr, 0, sizeof(genlhdr));
  genlhdr.cmd = CTRL_CMD_GETFAMILY;
  netlink_init(nlmsg, GENL_ID_CTRL, 0, &genlhdr, sizeof(genlhdr));
  netlink_attr(nlmsg, CTRL_ATTR_FAMILY_NAME, family_name,
               strnlen(family_name, GENL_NAMSIZ - 1) + 1);
  int n = 0;
  int err = netlink_send_ext(nlmsg, sock, GENL_ID_CTRL, &n, dofail);
  if (err < 0) {
    return -1;
  }
  uint16_t id = 0;
  struct nlattr* attr = (struct nlattr*)(nlmsg->buf + NLMSG_HDRLEN +
                                         NLMSG_ALIGN(sizeof(genlhdr)));
  for (; (char*)attr < nlmsg->buf + n;
       attr = (struct nlattr*)((char*)attr + NLMSG_ALIGN(attr->nla_len))) {
    if (attr->nla_type == CTRL_ATTR_FAMILY_ID) {
      id = *(uint16_t*)(attr + 1);
      break;
    }
  }
  if (!id) {
    errno = EINVAL;
    return -1;
  }
  recv(sock, nlmsg->buf, sizeof(nlmsg->buf), 0);
  return id;
}

static void netlink_add_device_impl(struct nlmsg* nlmsg, const char* type,
                                    const char* name, bool up)
{
  struct ifinfomsg hdr;
  memset(&hdr, 0, sizeof(hdr));
  if (up)
    hdr.ifi_flags = hdr.ifi_change = IFF_UP;
  netlink_init(nlmsg, RTM_NEWLINK, NLM_F_EXCL | NLM_F_CREATE, &hdr,
               sizeof(hdr));
  if (name)
    netlink_attr(nlmsg, IFLA_IFNAME, name, strlen(name));
  netlink_nest(nlmsg, IFLA_LINKINFO);
  netlink_attr(nlmsg, IFLA_INFO_KIND, type, strlen(type));
}

static void netlink_device_change(struct nlmsg* nlmsg, int sock,
                                  const char* name, bool up, const char* master,
                                  const void* mac, int macsize,
                                  const char* new_name)
{
  struct ifinfomsg hdr;
  memset(&hdr, 0, sizeof(hdr));
  if (up)
    hdr.ifi_flags = hdr.ifi_change = IFF_UP;
  hdr.ifi_index = if_nametoindex(name);
  netlink_init(nlmsg, RTM_NEWLINK, 0, &hdr, sizeof(hdr));
  if (new_name)
    netlink_attr(nlmsg, IFLA_IFNAME, new_name, strlen(new_name));
  if (master) {
    int ifindex = if_nametoindex(master);
    netlink_attr(nlmsg, IFLA_MASTER, &ifindex, sizeof(ifindex));
  }
  if (macsize)
    netlink_attr(nlmsg, IFLA_ADDRESS, mac, macsize);
  int err = netlink_send(nlmsg, sock);
  if (err < 0) {
  }
}

static struct nlmsg nlmsg;

//% This code is derived from puff.{c,h}, found in the zlib development. The
//% original files come with the following copyright notice:

//% Copyright (C) 2002-2013 Mark Adler, all rights reserved
//% version 2.3, 21 Jan 2013
//% This software is provided 'as-is', without any express or implied
//% warranty.  In no event will the author be held liable for any damages
//% arising from the use of this software.
//% Permission is granted to anyone to use this software for any purpose,
//% including commercial applications, and to alter it and redistribute it
//% freely, subject to the following restrictions:
//% 1. The origin of this software must not be misrepresented; you must not
//%    claim that you wrote the original software. If you use this software
//%    in a product, an acknowledgment in the product documentation would be
//%    appreciated but is not required.
//% 2. Altered source versions must be plainly marked as such, and must not be
//%    misrepresented as being the original software.
//% 3. This notice may not be removed or altered from any source distribution.
//% Mark Adler    madler@alumni.caltech.edu

//% BEGIN CODE DERIVED FROM puff.{c,h}

#define MAXBITS 15
#define MAXLCODES 286
#define MAXDCODES 30
#define MAXCODES (MAXLCODES + MAXDCODES)
#define FIXLCODES 288

struct puff_state {
  unsigned char* out;
  unsigned long outlen;
  unsigned long outcnt;
  const unsigned char* in;
  unsigned long inlen;
  unsigned long incnt;
  int bitbuf;
  int bitcnt;
  jmp_buf env;
};
static int puff_bits(struct puff_state* s, int need)
{
  long val = s->bitbuf;
  while (s->bitcnt < need) {
    if (s->incnt == s->inlen)
      longjmp(s->env, 1);
    val |= (long)(s->in[s->incnt++]) << s->bitcnt;
    s->bitcnt += 8;
  }
  s->bitbuf = (int)(val >> need);
  s->bitcnt -= need;
  return (int)(val & ((1L << need) - 1));
}
static int puff_stored(struct puff_state* s)
{
  s->bitbuf = 0;
  s->bitcnt = 0;
  if (s->incnt + 4 > s->inlen)
    return 2;
  unsigned len = s->in[s->incnt++];
  len |= s->in[s->incnt++] << 8;
  if (s->in[s->incnt++] != (~len & 0xff) ||
      s->in[s->incnt++] != ((~len >> 8) & 0xff))
    return -2;
  if (s->incnt + len > s->inlen)
    return 2;
  if (s->outcnt + len > s->outlen)
    return 1;
  for (; len--; s->outcnt++, s->incnt++) {
    if (s->in[s->incnt])
      s->out[s->outcnt] = s->in[s->incnt];
  }
  return 0;
}
struct puff_huffman {
  short* count;
  short* symbol;
};
static int puff_decode(struct puff_state* s, const struct puff_huffman* h)
{
  int first = 0;
  int index = 0;
  int bitbuf = s->bitbuf;
  int left = s->bitcnt;
  int code = first = index = 0;
  int len = 1;
  short* next = h->count + 1;
  while (1) {
    while (left--) {
      code |= bitbuf & 1;
      bitbuf >>= 1;
      int count = *next++;
      if (code - count < first) {
        s->bitbuf = bitbuf;
        s->bitcnt = (s->bitcnt - len) & 7;
        return h->symbol[index + (code - first)];
      }
      index += count;
      first += count;
      first <<= 1;
      code <<= 1;
      len++;
    }
    left = (MAXBITS + 1) - len;
    if (left == 0)
      break;
    if (s->incnt == s->inlen)
      longjmp(s->env, 1);
    bitbuf = s->in[s->incnt++];
    if (left > 8)
      left = 8;
  }
  return -10;
}
static int puff_construct(struct puff_huffman* h, const short* length, int n)
{
  int len;
  for (len = 0; len <= MAXBITS; len++)
    h->count[len] = 0;
  int symbol;
  for (symbol = 0; symbol < n; symbol++)
    (h->count[length[symbol]])++;
  if (h->count[0] == n)
    return 0;
  int left = 1;
  for (len = 1; len <= MAXBITS; len++) {
    left <<= 1;
    left -= h->count[len];
    if (left < 0)
      return left;
  }
  short offs[MAXBITS + 1];
  offs[1] = 0;
  for (len = 1; len < MAXBITS; len++)
    offs[len + 1] = offs[len] + h->count[len];
  for (symbol = 0; symbol < n; symbol++)
    if (length[symbol] != 0)
      h->symbol[offs[length[symbol]]++] = symbol;
  return left;
}
static int puff_codes(struct puff_state* s, const struct puff_huffman* lencode,
                      const struct puff_huffman* distcode)
{
  static const short lens[29] = {3,  4,  5,  6,   7,   8,   9,   10,  11, 13,
                                 15, 17, 19, 23,  27,  31,  35,  43,  51, 59,
                                 67, 83, 99, 115, 131, 163, 195, 227, 258};
  static const short lext[29] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2,
                                 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 0};
  static const short dists[30] = {
      1,    2,    3,    4,    5,    7,    9,    13,    17,    25,
      33,   49,   65,   97,   129,  193,  257,  385,   513,   769,
      1025, 1537, 2049, 3073, 4097, 6145, 8193, 12289, 16385, 24577};
  static const short dext[30] = {0, 0, 0,  0,  1,  1,  2,  2,  3,  3,
                                 4, 4, 5,  5,  6,  6,  7,  7,  8,  8,
                                 9, 9, 10, 10, 11, 11, 12, 12, 13, 13};
  int symbol;
  do {
    symbol = puff_decode(s, lencode);
    if (symbol < 0)
      return symbol;
    if (symbol < 256) {
      if (s->outcnt == s->outlen)
        return 1;
      if (symbol)
        s->out[s->outcnt] = symbol;
      s->outcnt++;
    } else if (symbol > 256) {
      symbol -= 257;
      if (symbol >= 29)
        return -10;
      int len = lens[symbol] + puff_bits(s, lext[symbol]);
      symbol = puff_decode(s, distcode);
      if (symbol < 0)
        return symbol;
      unsigned dist = dists[symbol] + puff_bits(s, dext[symbol]);
      if (dist > s->outcnt)
        return -11;
      if (s->outcnt + len > s->outlen)
        return 1;
      while (len--) {
        if (dist <= s->outcnt && s->out[s->outcnt - dist])
          s->out[s->outcnt] = s->out[s->outcnt - dist];
        s->outcnt++;
      }
    }
  } while (symbol != 256);
  return 0;
}
static int puff_fixed(struct puff_state* s)
{
  static int virgin = 1;
  static short lencnt[MAXBITS + 1], lensym[FIXLCODES];
  static short distcnt[MAXBITS + 1], distsym[MAXDCODES];
  static struct puff_huffman lencode, distcode;
  if (virgin) {
    lencode.count = lencnt;
    lencode.symbol = lensym;
    distcode.count = distcnt;
    distcode.symbol = distsym;
    short lengths[FIXLCODES];
    int symbol;
    for (symbol = 0; symbol < 144; symbol++)
      lengths[symbol] = 8;
    for (; symbol < 256; symbol++)
      lengths[symbol] = 9;
    for (; symbol < 280; symbol++)
      lengths[symbol] = 7;
    for (; symbol < FIXLCODES; symbol++)
      lengths[symbol] = 8;
    puff_construct(&lencode, lengths, FIXLCODES);
    for (symbol = 0; symbol < MAXDCODES; symbol++)
      lengths[symbol] = 5;
    puff_construct(&distcode, lengths, MAXDCODES);
    virgin = 0;
  }
  return puff_codes(s, &lencode, &distcode);
}
static int puff_dynamic(struct puff_state* s)
{
  static const short order[19] = {16, 17, 18, 0, 8,  7, 9,  6, 10, 5,
                                  11, 4,  12, 3, 13, 2, 14, 1, 15};
  int nlen = puff_bits(s, 5) + 257;
  int ndist = puff_bits(s, 5) + 1;
  int ncode = puff_bits(s, 4) + 4;
  if (nlen > MAXLCODES || ndist > MAXDCODES)
    return -3;
  short lengths[MAXCODES];
  int index;
  for (index = 0; index < ncode; index++)
    lengths[order[index]] = puff_bits(s, 3);
  for (; index < 19; index++)
    lengths[order[index]] = 0;
  short lencnt[MAXBITS + 1], lensym[MAXLCODES];
  struct puff_huffman lencode = {lencnt, lensym};
  int err = puff_construct(&lencode, lengths, 19);
  if (err != 0)
    return -4;
  index = 0;
  while (index < nlen + ndist) {
    int symbol;
    int len;
    symbol = puff_decode(s, &lencode);
    if (symbol < 0)
      return symbol;
    if (symbol < 16)
      lengths[index++] = symbol;
    else {
      len = 0;
      if (symbol == 16) {
        if (index == 0)
          return -5;
        len = lengths[index - 1];
        symbol = 3 + puff_bits(s, 2);
      } else if (symbol == 17)
        symbol = 3 + puff_bits(s, 3);
      else
        symbol = 11 + puff_bits(s, 7);
      if (index + symbol > nlen + ndist)
        return -6;
      while (symbol--)
        lengths[index++] = len;
    }
  }
  if (lengths[256] == 0)
    return -9;
  err = puff_construct(&lencode, lengths, nlen);
  if (err && (err < 0 || nlen != lencode.count[0] + lencode.count[1]))
    return -7;
  short distcnt[MAXBITS + 1], distsym[MAXDCODES];
  struct puff_huffman distcode = {distcnt, distsym};
  err = puff_construct(&distcode, lengths + nlen, ndist);
  if (err && (err < 0 || ndist != distcode.count[0] + distcode.count[1]))
    return -8;
  return puff_codes(s, &lencode, &distcode);
}
static int puff(unsigned char* dest, unsigned long* destlen,
                const unsigned char* source, unsigned long sourcelen)
{
  struct puff_state s = {
      .out = dest,
      .outlen = *destlen,
      .outcnt = 0,
      .in = source,
      .inlen = sourcelen,
      .incnt = 0,
      .bitbuf = 0,
      .bitcnt = 0,
  };
  int err;
  if (setjmp(s.env) != 0)
    err = 2;
  else {
    int last;
    do {
      last = puff_bits(&s, 1);
      int type = puff_bits(&s, 2);
      err = type == 0 ? puff_stored(&s)
                      : (type == 1 ? puff_fixed(&s)
                                   : (type == 2 ? puff_dynamic(&s) : -1));
      if (err != 0)
        break;
    } while (!last);
  }
  *destlen = s.outcnt;
  return err;
}

//% END CODE DERIVED FROM puff.{c,h}

#define ZLIB_HEADER_WIDTH 2

static int puff_zlib_to_file(const unsigned char* source,
                             unsigned long sourcelen, int dest_fd)
{
  if (sourcelen < ZLIB_HEADER_WIDTH)
    return 0;
  source += ZLIB_HEADER_WIDTH;
  sourcelen -= ZLIB_HEADER_WIDTH;
  const unsigned long max_destlen = 132 << 20;
  void* ret = mmap(0, max_destlen, PROT_WRITE | PROT_READ,
                   MAP_PRIVATE | MAP_ANON, -1, 0);
  if (ret == MAP_FAILED)
    return -1;
  unsigned char* dest = (unsigned char*)ret;
  unsigned long destlen = max_destlen;
  int err = puff(dest, &destlen, source, sourcelen);
  if (err) {
    munmap(dest, max_destlen);
    errno = -err;
    return -1;
  }
  if (write(dest_fd, dest, destlen) != (ssize_t)destlen) {
    munmap(dest, max_destlen);
    return -1;
  }
  return munmap(dest, max_destlen);
}

static int setup_loop_device(unsigned char* data, unsigned long size,
                             const char* loopname, int* loopfd_p)
{
  int err = 0, loopfd = -1;
  int memfd = syscall(__NR_memfd_create, "syzkaller", 0);
  if (memfd == -1) {
    err = errno;
    goto error;
  }
  if (puff_zlib_to_file(data, size, memfd)) {
    err = errno;
    goto error_close_memfd;
  }
  loopfd = open(loopname, O_RDWR);
  if (loopfd == -1) {
    err = errno;
    goto error_close_memfd;
  }
  if (ioctl(loopfd, LOOP_SET_FD, memfd)) {
    if (errno != EBUSY) {
      err = errno;
      goto error_close_loop;
    }
    ioctl(loopfd, LOOP_CLR_FD, 0);
    usleep(1000);
    if (ioctl(loopfd, LOOP_SET_FD, memfd)) {
      err = errno;
      goto error_close_loop;
    }
  }
  close(memfd);
  *loopfd_p = loopfd;
  return 0;

error_close_loop:
  close(loopfd);
error_close_memfd:
  close(memfd);
error:
  errno = err;
  return -1;
}

static void reset_loop_device(const char* loopname)
{
  int loopfd = open(loopname, O_RDWR);
  if (loopfd == -1) {
    return;
  }
  if (ioctl(loopfd, LOOP_CLR_FD, 0)) {
  }
  close(loopfd);
}

static long syz_mount_image(volatile long fsarg, volatile long dir,
                            volatile long flags, volatile long optsarg,
                            volatile long change_dir,
                            volatile unsigned long size, volatile long image)
{
  unsigned char* data = (unsigned char*)image;
  int res = -1, err = 0, need_loop_device = !!size;
  char* mount_opts = (char*)optsarg;
  char* target = (char*)dir;
  char* fs = (char*)fsarg;
  char* source = NULL;
  char loopname[64];
  if (need_loop_device) {
    int loopfd;
    memset(loopname, 0, sizeof(loopname));
    snprintf(loopname, sizeof(loopname), "/dev/loop%llu", procid);
    if (setup_loop_device(data, size, loopname, &loopfd) == -1)
      return -1;
    close(loopfd);
    source = loopname;
  }
  mkdir(target, 0777);
  char opts[256];
  memset(opts, 0, sizeof(opts));
  if (strlen(mount_opts) > (sizeof(opts) - 32)) {
  }
  strncpy(opts, mount_opts, sizeof(opts) - 32);
  if (strcmp(fs, "iso9660") == 0) {
    flags |= MS_RDONLY;
  } else if (strncmp(fs, "ext", 3) == 0) {
    bool has_remount_ro = false;
    char* remount_ro_start = strstr(opts, "errors=remount-ro");
    if (remount_ro_start != NULL) {
      char after = *(remount_ro_start + strlen("errors=remount-ro"));
      char before = remount_ro_start == opts ? '\0' : *(remount_ro_start - 1);
      has_remount_ro = ((before == '\0' || before == ',') &&
                        (after == '\0' || after == ','));
    }
    if (strstr(opts, "errors=panic") || !has_remount_ro)
      strcat(opts, ",errors=continue");
  } else if (strcmp(fs, "xfs") == 0) {
    strcat(opts, ",nouuid");
  } else if (strncmp(fs, "gfs2", 4) == 0 &&
             (strstr(opts, "errors=panic") || strstr(opts, "debug"))) {
    strcat(opts, ",errors=withdraw");
  }
  res = mount(source, target, fs, flags, opts);
  if (res == -1) {
    err = errno;
    goto error_clear_loop;
  }
  res = open(target, O_RDONLY | O_DIRECTORY);
  if (res == -1) {
    err = errno;
    goto error_clear_loop;
  }
  if (change_dir) {
    res = chdir(target);
    if (res == -1) {
      err = errno;
    }
  }

error_clear_loop:
  if (need_loop_device)
    reset_loop_device(loopname);
  errno = err;
  return res;
}

#define FS_IOC_SETFLAGS _IOW('f', 2, long)
static void remove_dir(const char* dir)
{
  int iter = 0;
  DIR* dp = 0;
  const int umount_flags = MNT_FORCE | UMOUNT_NOFOLLOW;

retry:
  while (umount2(dir, umount_flags) == 0) {
  }
  dp = opendir(dir);
  if (dp == NULL) {
    if (errno == EMFILE) {
      exit(1);
    }
    exit(1);
  }
  struct dirent* ep = 0;
  while ((ep = readdir(dp))) {
    if (strcmp(ep->d_name, ".") == 0 || strcmp(ep->d_name, "..") == 0)
      continue;
    char filename[FILENAME_MAX];
    snprintf(filename, sizeof(filename), "%s/%s", dir, ep->d_name);
    while (umount2(filename, umount_flags) == 0) {
    }
    struct stat st;
    if (lstat(filename, &st))
      exit(1);
    if (S_ISDIR(st.st_mode)) {
      remove_dir(filename);
      continue;
    }
    int i;
    for (i = 0;; i++) {
      if (unlink(filename) == 0)
        break;
      if (errno == EPERM) {
        int fd = open(filename, O_RDONLY);
        if (fd != -1) {
          long flags = 0;
          if (ioctl(fd, FS_IOC_SETFLAGS, &flags) == 0) {
          }
          close(fd);
          continue;
        }
      }
      if (errno == EROFS) {
        break;
      }
      if (errno != EBUSY || i > 100)
        exit(1);
      if (umount2(filename, umount_flags))
        exit(1);
    }
  }
  closedir(dp);
  for (int i = 0;; i++) {
    if (rmdir(dir) == 0)
      break;
    if (i < 100) {
      if (errno == EPERM) {
        int fd = open(dir, O_RDONLY);
        if (fd != -1) {
          long flags = 0;
          if (ioctl(fd, FS_IOC_SETFLAGS, &flags) == 0) {
          }
          close(fd);
          continue;
        }
      }
      if (errno == EROFS) {
        break;
      }
      if (errno == EBUSY) {
        if (umount2(dir, umount_flags))
          exit(1);
        continue;
      }
      if (errno == ENOTEMPTY) {
        if (iter < 100) {
          iter++;
          goto retry;
        }
      }
    }
    exit(1);
  }
}

static void kill_and_wait(int pid, int* status)
{
  kill(-pid, SIGKILL);
  kill(pid, SIGKILL);
  for (int i = 0; i < 100; i++) {
    if (waitpid(-1, status, WNOHANG | __WALL) == pid)
      return;
    usleep(1000);
  }
  DIR* dir = opendir("/sys/fs/fuse/connections");
  if (dir) {
    for (;;) {
      struct dirent* ent = readdir(dir);
      if (!ent)
        break;
      if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0)
        continue;
      char abort[300];
      snprintf(abort, sizeof(abort), "/sys/fs/fuse/connections/%s/abort",
               ent->d_name);
      int fd = open(abort, O_WRONLY);
      if (fd == -1) {
        continue;
      }
      if (write(fd, abort, 1) < 0) {
      }
      close(fd);
    }
    closedir(dir);
  } else {
  }
  while (waitpid(-1, status, __WALL) != pid) {
  }
}

static void reset_loop()
{
  char buf[64];
  snprintf(buf, sizeof(buf), "/dev/loop%llu", procid);
  int loopfd = open(buf, O_RDWR);
  if (loopfd != -1) {
    ioctl(loopfd, LOOP_CLR_FD, 0);
    close(loopfd);
  }
}

static void setup_test()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  setpgrp();
  write_file("/proc/self/oom_score_adj", "1000");
  if (symlink("/dev/binderfs", "./binderfs")) {
  }
}

#define NL802154_CMD_SET_SHORT_ADDR 11
#define NL802154_ATTR_IFINDEX 3
#define NL802154_ATTR_SHORT_ADDR 10

static const char* setup_802154()
{
  const char* error = NULL;
  int sock_generic = -1;
  int sock_route = socket(AF_NETLINK, SOCK_RAW, NETLINK_ROUTE);
  if (sock_route == -1) {
    error = "socket(AF_NETLINK, SOCK_RAW, NETLINK_ROUTE) failed";
    goto fail;
  }
  sock_generic = socket(AF_NETLINK, SOCK_RAW, NETLINK_GENERIC);
  if (sock_generic == -1) {
    error = "socket(AF_NETLINK, SOCK_RAW, NETLINK_GENERIC) failed";
    goto fail;
  }
  {
    int nl802154_family_id =
        netlink_query_family_id(&nlmsg, sock_generic, "nl802154", true);
    if (nl802154_family_id < 0) {
      error = "netlink_query_family_id failed";
      goto fail;
    }
    for (int i = 0; i < 2; i++) {
      char devname[] = "wpan0";
      devname[strlen(devname) - 1] += i;
      uint64_t hwaddr = 0xaaaaaaaaaaaa0002 + (i << 8);
      uint16_t shortaddr = 0xaaa0 + i;
      int ifindex = if_nametoindex(devname);
      struct genlmsghdr genlhdr;
      memset(&genlhdr, 0, sizeof(genlhdr));
      genlhdr.cmd = NL802154_CMD_SET_SHORT_ADDR;
      netlink_init(&nlmsg, nl802154_family_id, 0, &genlhdr, sizeof(genlhdr));
      netlink_attr(&nlmsg, NL802154_ATTR_IFINDEX, &ifindex, sizeof(ifindex));
      netlink_attr(&nlmsg, NL802154_ATTR_SHORT_ADDR, &shortaddr,
                   sizeof(shortaddr));
      if (netlink_send(&nlmsg, sock_generic) < 0) {
        error = "NL802154_CMD_SET_SHORT_ADDR failed";
        goto fail;
      }
      netlink_device_change(&nlmsg, sock_route, devname, true, 0, &hwaddr,
                            sizeof(hwaddr), 0);
      if (i == 0) {
        netlink_add_device_impl(&nlmsg, "lowpan", "lowpan0", false);
        netlink_done(&nlmsg);
        netlink_attr(&nlmsg, IFLA_LINK, &ifindex, sizeof(ifindex));
        if (netlink_send(&nlmsg, sock_route) < 0) {
          error = "netlink: adding device lowpan0 type lowpan link wpan0";
          goto fail;
        }
      }
    }
  }
fail:
  close(sock_route);
  close(sock_generic);
  return error;
}

static void execute_one(void);

#define WAIT_FLAGS __WALL

static void loop(void)
{
  int iter = 0;
  for (;; iter++) {
    char cwdbuf[32];
    sprintf(cwdbuf, "./%d", iter);
    if (mkdir(cwdbuf, 0777))
      exit(1);
    reset_loop();
    int pid = fork();
    if (pid < 0)
      exit(1);
    if (pid == 0) {
      if (chdir(cwdbuf))
        exit(1);
      setup_test();
      execute_one();
      exit(0);
    }
    int status = 0;
    uint64_t start = current_time_ms();
    for (;;) {
      sleep_ms(10);
      if (waitpid(-1, &status, WNOHANG | WAIT_FLAGS) == pid)
        break;
      if (current_time_ms() - start < 5000)
        continue;
      kill_and_wait(pid, &status);
      break;
    }
    remove_dir(cwdbuf);
  }
}

uint64_t r[4] = {0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff,
                 0xffffffffffffffff};

void execute_one(void)
{
  intptr_t res = 0;
  if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {
  }
  //  syz_mount_image$hfs arguments: [
  //    fs: ptr[in, buffer] {
  //      buffer: {68 66 73 00} (length 0x4)
  //    }
  //    dir: ptr[in, buffer] {
  //      buffer: {2e 2f 62 75 73 00} (length 0x6)
  //    }
  //    flags: mount_flags = 0x808408 (8 bytes)
  //    opts: ptr[inout, array[ANYUNION]] {
  //      array[ANYUNION] {
  //        union ANYUNION {
  //          ANYBLOB: buffer: {63 6f 64 65 70 61 67 65 3d 75 74 66 38 2c 66 69
  //          6c 65 5f 75 6d 61 73 6b 3d 30 30 30 30 30 30 30 30 30 30 30 30 30
  //          30 30 30 30 30 30 30 30 30 33 2c 69 6f 63 68 61 72 73 65 74 3d 63
  //          70 37 37 35 2c 71 75 69 65 74 2c 00 8f 78 81 d1 85 c3 5a 6a 28 ef
  //          06 c5 b8 56 28 f1 2a 02 24 8d e2 49 c2 a3 38 d0 49 16 63 71 58 37
  //          81 68 0d 17 1f 47} (length 0x6e)
  //        }
  //      }
  //    }
  //    chdir: int8 = 0x1 (1 bytes)
  //    size: len = 0x2df (8 bytes)
  //    img: ptr[in, buffer] {
  //      buffer: (compressed buffer with length 0x2df)
  //    }
  //  ]
  //  returns fd_dir
  memcpy((void*)0x200000000080, "hfs\000", 4);
  memcpy((void*)0x200000000040, "./bus\000", 6);
  memcpy((void*)0x200000000380,
         "\x63\x6f\x64\x65\x70\x61\x67\x65\x3d\x75\x74\x66\x38\x2c\x66\x69\x6c"
         "\x65\x5f\x75\x6d\x61\x73\x6b\x3d\x30\x30\x30\x30\x30\x30\x30\x30\x30"
         "\x30\x30\x30\x30\x30\x30\x30\x30\x30\x30\x30\x30\x30\x33\x2c\x69\x6f"
         "\x63\x68\x61\x72\x73\x65\x74\x3d\x63\x70\x37\x37\x35\x2c\x71\x75\x69"
         "\x65\x74\x2c\x00\x8f\x78\x81\xd1\x85\xc3\x5a\x6a\x28\xef\x06\xc5\xb8"
         "\x56\x28\xf1\x2a\x02\x24\x8d\xe2\x49\xc2\xa3\x38\xd0\x49\x16\x63\x71"
         "\x58\x37\x81\x68\x0d\x17\x1f\x47",
         110);
  memcpy(
      (void*)0x200000000400,
      "\x78\x9c\xec\xdd\x3f\x6f\xd3\x4e\x1c\xc7\xf1\xcf\x39\x49\x9b\xfe\x51\x7f"
      "\xfe\xb5\x45\x48\x2c\xa0\x42\x25\x58\x2a\x0a\x0c\x88\x25\x08\x65\x65\x67"
      "\x42\x40\x93\x4a\x15\x51\x11\x6d\x91\x80\x85\x82\x18\x11\x0f\x80\x9d\xa7"
      "\xc0\x83\x60\x01\xf1\x04\x60\x62\xe2\x01\x74\x33\xba\xf3\xd9\x75\x52\xc7"
      "\x69\xa0\x89\xdb\xf2\x7e\x49\x89\x9c\xf3\xdd\xf9\xeb\xda\x17\xdf\xd7\x52"
      "\x6a\x01\xf8\x67\xdd\x69\x7e\xff\x78\xfd\xa7\x7d\x19\xa9\xa2\x8a\xa4\x5b"
      "\x52\x20\xa9\x2e\x55\x25\x9d\xd1\xd9\xfa\xb3\xcd\x9d\x8d\x9d\x4e\xbb\x55"
      "\xd4\x51\xc5\xb5\xb0\x2f\xa3\xb8\xa5\x39\x50\x67\x6d\xb3\x9d\xd7\xd4\xb6"
      "\x73\x2d\xbc\xd0\x7e\xaa\x6a\x36\x5b\x86\xd1\x88\xa2\xe8\xf6\x8f\xb2\x83"
      "\x40\xe9\xdc\xe8\xcf\x11\x48\x93\x7e\x1c\xba\xf5\xf5\x31\xc7\x35\x2a\xbb"
      "\xd2\xf9\xb2\x63\x18\xb7\xec\x01\x36\x7b\xda\xd3\x73\xcd\x95\x18\x0e\x00"
      "\xe0\x18\xf0\xd7\xff\xc0\x5f\x26\x66\x5d\x91\x51\x10\x48\xcb\xfe\xb2\x7f"
      "\xaa\xae\xff\x7b\x65\x07\x70\xb4\x6e\x74\x0e\x14\x45\x85\x0d\x32\xd7\x7f"
      "\x37\xbb\x8b\x8c\x3d\xbe\xff\xb9\x55\xfb\xf9\x9e\x4b\xe1\xec\xfa\x20\xc9"
      "\x12\x0f\x13\x4c\xad\xe7\xf3\x84\xe2\x33\xab\x6b\x82\x69\x06\x65\x95\x2e"
      "\x96\x60\x6a\x7d\xa3\xaa\x95\xb5\xd7\x6a\x05\x7a\xa3\x86\x97\xa9\xb6\xe8"
      "\xde\x5b\xf1\xa9\x9b\x18\x10\xed\x52\x4e\x6e\x5a\xa0\x7f\x6f\x35\xdd\x9d"
      "\x8e\xf7\xc6\xcd\x28\x7b\x25\x21\xad\x6f\x74\xda\x93\x76\x21\x27\xfe\x85"
      "\xe1\xb6\xf8\xf7\xcc\x67\xf3\xd5\xdc\x37\xa1\x3e\xa8\x95\xce\xff\xaa\x91"
      "\xb1\x87\xc9\x1d\xa9\xb0\xe7\x48\x05\x35\x1b\xff\xd5\xfe\x3d\xce\xb8\x56"
      "\xb6\x96\x7c\xda\xdf\x68\x34\x82\xae\x2a\xff\xbb\x8d\x9c\xf3\x5b\xf0\x06"
      "\xec\x65\x3d\x3f\x23\xc9\xf6\x99\xdc\x20\xd8\x4d\x23\x28\x8a\xd3\x6d\x7b"
      "\x5e\xdd\xb7\x15\xe2\xbd\x5b\x1d\xd0\x6a\x21\xaf\x55\x98\x7e\xea\xd3\x6a"
      "\xb1\xab\x55\xc5\x9f\x09\x2b\x6b\x4f\x3a\x85\xb7\x52\x46\x23\xd9\x45\xf3"
      "\xde\xdc\x33\x4b\xfa\xa5\x4f\x6a\x66\xe6\xff\x81\x8d\x6f\x59\x99\x91\x59"
      "\xf4\x55\x6f\x5c\x4d\x7f\x66\xc4\xfb\x33\x91\x5f\x33\xfd\xdb\xf4\x74\xb7"
      "\x3f\x5c\x2e\xf4\xd6\x9c\x1c\x6a\xbf\xe0\x0d\x77\xb7\xec\x9d\x1e\xe9\xa6"
      "\xe6\xb6\x5f\xbc\x7c\x5c\xe9\x74\xda\x5b\x76\xe1\x61\xce\xc2\xd3\xd9\x2d"
      "\xe3\x4b\x6a\x6f\xa5\xdc\x3a\xa3\x5f\xa8\xa8\xa0\x8e\x76\xf7\x4b\x22\xeb"
      "\x55\x14\x1d\xb6\xe7\x68\x94\xc1\x5f\x39\xd2\x0e\xed\xf7\x47\x5a\x62\x87"
      "\x4f\x5e\x65\x3b\xca\xd2\x92\x60\xdc\x87\xe9\xd4\x2d\xd8\x91\x92\xb3\xaa"
      "\xf9\x45\x45\x27\xe4\xc9\x59\x88\x22\xa9\xcf\xaa\x51\x7d\x4d\xe1\x38\xd9"
      "\x36\xc9\x41\xf7\x05\x53\x25\x07\x84\x71\xb3\xf3\x2e\x13\xe7\x7f\x6e\x26"
      "\xef\x67\x75\x2e\x45\xb2\x6f\x61\xc1\x3c\xbd\x38\xc9\x54\x57\x8f\xab\x69"
      "\x06\xd7\x3d\x15\x9c\x77\xef\xd3\x43\x65\x70\x33\xfd\x33\xb8\xcc\x16\xaf"
      "\xf5\xc9\x19\x5d\xce\x75\xf1\xb2\x74\x29\x53\x68\x54\xb8\xc5\xd0\xc7\x79"
      "\x4a\x98\xa6\xbe\xe9\x01\xf7\xff\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x4e\x9a\x23\xfc\x39\x41\xf2\x4b\xc6\x03\xab\x4a\xde"
      "\x45\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x4e\xbc\x3f\x7a\xfe\x6f\xde\xff\x88\x77\xcf\xff\x0d\xc7\xf5\xfc\xdf\xe2"
      "\x27\x03\x01\x38\x94\xdf\x01\x00\x00\xff\xff\x98\xce\x73\x7c",
      735);
  syz_mount_image(
      /*fs=*/0x200000000080, /*dir=*/0x200000000040,
      /*flags=MS_I_VERSION|MS_SILENT|MS_NOEXEC|MS_NOATIME*/ 0x808408,
      /*opts=*/0x200000000380, /*chdir=*/1, /*size=*/0x2df,
      /*img=*/0x200000000400);
  //  sync arguments: [
  //  ]
  syscall(__NR_sync);
  //  openat arguments: [
  //    fd: fd_dir (resource)
  //    file: nil
  //    flags: open_flags = 0x143042 (4 bytes)
  //    mode: open_mode = 0x0 (2 bytes)
  //  ]
  //  returns fd
  res = syscall(__NR_openat, /*fd=*/0xffffff9c, /*file=*/0ul,
                /*flags=O_SYNC|O_NOATIME|O_CREAT|FASYNC|O_RDWR*/ 0x143042,
                /*mode=*/0);
  if (res != -1)
    r[0] = res;
  //  openat arguments: [
  //    fd: fd_dir (resource)
  //    file: nil
  //    flags: open_flags = 0x143042 (4 bytes)
  //    mode: open_mode = 0x0 (2 bytes)
  //  ]
  //  returns fd
  res = syscall(__NR_openat, /*fd=*/0xffffff9c, /*file=*/0ul,
                /*flags=O_SYNC|O_NOATIME|O_CREAT|FASYNC|O_RDWR*/ 0x143042,
                /*mode=*/0);
  if (res != -1)
    r[1] = res;
  //  creat arguments: [
  //    file: nil
  //    mode: open_mode = 0x119 (8 bytes)
  //  ]
  //  returns fd
  syscall(__NR_creat, /*file=*/0ul,
          /*mode=S_IXOTH|S_IXGRP|S_IWGRP|S_IRUSR*/ 0x119ul);
  //  symlink arguments: [
  //    old: nil
  //    new: nil
  //  ]
  syscall(__NR_symlink, /*old=*/0ul, /*new=*/0ul);
  //  creat arguments: [
  //    file: nil
  //    mode: open_mode = 0x0 (8 bytes)
  //  ]
  //  returns fd
  res = syscall(__NR_creat, /*file=*/0ul, /*mode=*/0ul);
  if (res != -1)
    r[2] = res;
  //  unlinkat arguments: [
  //    fd: fd_dir (resource)
  //    path: nil
  //    flags: unlinkat_flags = 0x0 (8 bytes)
  //  ]
  syscall(__NR_unlinkat, /*fd=*/r[1], /*path=*/0ul, /*flags=*/0ul);
  //  openat$ipvs arguments: [
  //    fd: const = 0xffffffffffffff9c (8 bytes)
  //    file: nil
  //    flags: const = 0x2 (4 bytes)
  //    mode: const = 0x0 (2 bytes)
  //  ]
  //  returns fd
  syscall(__NR_openat, /*fd=*/0xffffffffffffff9cul, /*file=*/0ul, /*flags=*/2,
          /*mode=*/0);
  //  openat$cgroup_ro arguments: [
  //    fd: fd_cgroup (resource)
  //    file: nil
  //    flags: const = 0x275a (4 bytes)
  //    mode: const = 0x0 (2 bytes)
  //  ]
  //  returns fd
  syscall(__NR_openat, /*fd=*/0xffffff9c, /*file=*/0ul, /*flags=*/0x275a,
          /*mode=*/0);
  //  ioctl$FIONCLEX arguments: [
  //    fd: fd (resource)
  //    cmd: const = 0x5450 (4 bytes)
  //  ]
  syscall(__NR_ioctl, /*fd=*/r[2], /*cmd=*/0x5450, 0);
  //  syz_mount_image$romfs arguments: [
  //    fs: ptr[in, buffer] {
  //      buffer: {72 6f 6d 66 73 00} (length 0x6)
  //    }
  //    dir: ptr[in, buffer] {
  //      buffer: {2e 2f 66 69 6c 65 30 00} (length 0x8)
  //    }
  //    flags: mount_flags = 0x208008 (8 bytes)
  //    opts: ptr[inout, array[ANYUNION]] {
  //      array[ANYUNION] {
  //      }
  //    }
  //    chdir: int8 = 0x80 (1 bytes)
  //    size: len = 0x14e (8 bytes)
  //    img: ptr[in, buffer] {
  //      buffer: (compressed buffer with length 0x14e)
  //    }
  //  ]
  //  returns fd_dir
  memcpy((void*)0x200000000140, "romfs\000", 6);
  memcpy((void*)0x200000000280, "./file0\000", 8);
  memcpy(
      (void*)0x200000000e40,
      "\x78\x9c\xec\xda\xbf\x4a\xc3\x40\x1c\x07\xf0\x1f\x58\x11\x3a\x3a\x3a\x05"
      "\x2a\x51\xd0\xfc\xd7\xba\xea\x58\xdc\x7c\x83\xd0\xe6\xd2\xe0\xc5\x94\x44"
      "\x90\xf6\x05\xc4\x49\x50\x38\x07\x5f\x42\xf0\x09\x7c\x84\x8c\x6e\xba\x08"
      "\xfa\x12\x91\x98\xa3\x26\x51\x6c\x51\x21\x1d\xbe\x9f\xe5\xbe\xf0\x6b\xef"
      "\x7e\xbd\x2b\x37\x9d\x16\x47\xa1\xc5\x12\x8d\x68\x7b\x74\x75\xf4\xb2\x1a"
      "\x47\xa1\xd2\x75\xf6\xfa\xcc\x62\x2e\x15\x7a\x44\xa4\xe4\x21\xcd\xb2\x1b"
      "\x9d\xbe\x78\x9a\xd6\xd3\x8c\xf4\x6f\x3e\xd0\xac\xf5\xb7\x62\xec\x6c\xfa"
      "\xe2\xf0\x82\x05\xdc\xb3\x9b\x6e\x09\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\xe6\xa4\xb6\x65\x68\x0f\x45\x78\xce\x02"
      "\xee\x59\xa5\x6a\x32\x9e\x1c\xbb\x9c\x7b\x71\xd2\x50\x7b\x8d\x53\x15\xf9"
      "\x86\x8b\x98\xe0\xb7\xf9\xfe\x38\x95\xfa\xd6\x2b\x91\xba\x9f\xa7\x40\x1c"
      "\xc4\x79\xdd\xac\x7e\xff\x5a\x86\x8d\xa1\xe0\xcf\xf5\xfd\x35\x4e\xc3\x91"
      "\x91\x8c\x27\x5a\x10\xba\xbe\xe7\x7b\x27\xb6\xed\x74\xcd\x1d\xd3\xdc\xb5"
      "\x8d\x8f\xb9\x8c\xfa\x8c\xea\x9d\xec\x89\xd2\xec\xde\xd4\x29\x93\xa6\xf5"
      "\xd2\x7b\xb3\xc7\x79\xde\x9b\xc9\xf3\x6f\xad\x05\xe2\xf2\xac\xbe\xda\xe7"
      "\xf9\x23\x20\xfc\x35\xf4\x5a\xf8\x47\xfd\x2e\x2c\xd1\x42\xb4\x51\x0a\x33"
      "\x6e\x95\xd6\xcc\x7b\x67\x51\xb4\x97\x8b\x71\xb0\xe2\x74\x1e\xf2\xfb\x4f"
      "\xef\x47\x7c\x20\x8b\xff\xbb\x67\x72\x25\xaa\x96\x9a\xfa\xe1\x00\xf0\xb3"
      "\xf7\x00\x00\x00\xff\xff\x30\xa9\x3c\xd0",
      334);
  syz_mount_image(/*fs=*/0x200000000140, /*dir=*/0x200000000280,
                  /*flags=MS_SILENT|MS_RELATIME|MS_NOEXEC*/ 0x208008,
                  /*opts=*/0x200000000000, /*chdir=*/0x80, /*size=*/0x14e,
                  /*img=*/0x200000000e40);
  //  open arguments: [
  //    file: nil
  //    flags: open_flags = 0x0 (8 bytes)
  //    mode: open_mode = 0x194 (8 bytes)
  //  ]
  //  returns fd
  res = syscall(__NR_open, /*file=*/0ul, /*flags=*/0ul,
                /*mode=S_IROTH|S_IWGRP|S_IWUSR|S_IRUSR*/ 0x194ul);
  if (res != -1)
    r[3] = res;
  //  ioctl$FS_IOC_FSSETXATTR arguments: [
  //    fd: fd (resource)
  //    cmd: const = 0x401c5820 (4 bytes)
  //    arg: nil
  //  ]
  syscall(__NR_ioctl, /*fd=*/r[3], /*cmd=*/0x401c5820, /*arg=*/0ul);
  //  rename arguments: [
  //    old: ptr[in, buffer] {
  //      buffer: {2e 2f 66 69 6c 65 30 00} (length 0x8)
  //    }
  //    new: nil
  //  ]
  memcpy((void*)0x2000000003c0, "./file0\000", 8);
  syscall(__NR_rename, /*old=*/0x2000000003c0ul, /*new=*/0ul);
  //  openat arguments: [
  //    fd: fd_dir (resource)
  //    file: ptr[in, buffer] {
  //      buffer: {2e 2f 66 69 6c 65 31 00} (length 0x8)
  //    }
  //    flags: open_flags = 0x101142 (4 bytes)
  //    mode: open_mode = 0x0 (2 bytes)
  //  ]
  //  returns fd
  memcpy((void*)0x200000000080, "./file1\000", 8);
  syscall(__NR_openat, /*fd=*/0xffffff9c, /*file=*/0x200000000080ul,
          /*flags=O_SYNC|O_NOCTTY|O_CREAT|O_RDWR*/ 0x101142, /*mode=*/0);
  //  syncfs arguments: [
  //    fd: fd (resource)
  //  ]
  syscall(__NR_syncfs, /*fd=*/r[0]);
}
int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffffffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200000000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200001000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  const char* reason;
  (void)reason;
  if ((reason = setup_802154()))
    printf("the reproducer may not work as expected: 802154 injection setup "
           "failed: %s\n",
           reason);
  for (procid = 0; procid < 5; procid++) {
    if (fork() == 0) {
      use_temporary_dir();
      loop();
    }
  }
  sleep(1000000);
  return 0;
}
