name: Update Repository

on:
  schedule:
    - cron: '0 0 * * *'  # This will run at midnight UTC every day

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Download .tar.gz archive
        run: |
          curl -L -o archive.tar.gz https://storage.googleapis.com/artifacts.syzkaller.appspot.com/shared-files/repro-export/upstream.tar.gz

      - name: Unpack the archive
        run: |
          tar -xzf archive.tar.gz --strip-components=1

      - name: Commit changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "Update repository files from archive" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin HEAD:main
